http://www.academie-en-ligne.fr/Ressources/4/FR51/AL4FR51TEWB0111-Sequence-09.pdf

-------------------------------------------------------------------------
Ce cours est la propriété du Cned. Les images et textes intégrés à ce
cours sont la propriété de leurs auteurs et/ou ayants droit
respectifs. Tous ces éléments font l’ojet d’une protection par les
dispositions du code français de la propriété intellectuelle ainsi que
par les conventions internationales en vigueur. Ces contenus ne
peuvent être utilisés qu’à des fins strictement personnelles. Toute
reproduction, utilisation collective à quelque titre que ce soit, tout
usage commercial, ou toute mise à disposition de tiers d’un cours ou
d’une œuvre intégrée à ceux-ci sont strictement interdits.  
                                                            ©Cned-2009
-------------------------------------------------------------------------


* Sommaire de la séquence 9

Lire Le Roman de Renart

Séance 1: Découvrir Le Roman de Renart
Séance 2: Étudier les formes en -ant
Séance 3: Étudier le comique de situation
Séance 4: Distinguer les homonymes
Séance 5: Étudier la satire
Séance 6: Distinguer et utiliser les voix active et passive
Séance 7: Découvrir le personnage du Renard dans la littérature
Séance 8: Préparer l’évaluation de la lecture cursive du Chevalier au 
          bouclier vert d’Odile Weulersse
Séance 9: Je m’évalue

Compétences du socle commun évaluées dans cette séquence: On ne te
demandera pas d’évaluer la mobilisation de tous ces items, mais ce
sont néanmoins des compétences que tu vas mettre en pratique au cours
de cette séquence.

- écrire lisiblement un texte [COMPÉTENCE 1]
- Copier un texte sans erreurs [COMPÉTENCE 1]
- respecter les consignes d’écriture [COMPÉTENCE 1]
- rédiger un texte bref [COMPÉTENCE 1]
- utiliser les principales règles orthographiques [COMPÉTENCE 1]
- mémoriser des textes patrimoniaux [COMPÉTENCE 1]
- s’appuyer sur des méthodes de travail (organiser son temps, planifier 
  son travail, consulter spontanément un dictionnaire, une encyclopédie ..., 
  se concentrer, mémoriser) [COMPÉTENCE 7]
- rechercher l’information utile, l’analyser, la trier, la hiérachiser, 
  l’organiser, la synthétiser [COMPÉTENCE 7]
- identifier, expliquer, rectifier une erreur [COMPÉTENCE 7]
- savoir s’auto-évaluer [COMPÉTENCE 7]


* Séance 1

** Découvrir Le roman de Renart

Dans cette séquence, tu vas étudier des épisodes d’une œuvre très
célèbre du Moyen Âge : le Roman de Renart. Parallèlement, en lecture
cursive, tu devras lire un roman de littérature de jeunesse dont
l’histoire se passe aussi au Moyen Âge. Il s’agit du Chevalier au
bouclier vert d’Odile Weulersse. Pense à te procurer ce livre et à le
lire avant l’évaluation de la séquence 9.

Pour ton étude du Roman de Renart, voici quelques précisions:

Tout d’abord, contrairement à ce que le titre pourrait laisser croire,
le Roman de Renart n’est pas un roman ! le « roman » était la langue
que l’on parlait entre le latin et l’ancien français. Les textes de
l’époque étaient écrits soit en latin, soit en roman. Ces derniers
étaient d’abord appelés « romans » en références à la langue
utilisée. Puis le nom « roman » a désigné les fictions racontées en
langue romane. Comme la langue a beaucoup changé depuis le moyen âge,
tu vas lire une traduction du texte original.

Ensuite, il ne s’agit pas d’un roman comme ceux que tu peux lire
aujourd’hui : Le Roman de Renart a été écrit en vers, le plus souvent
en octosyllabes (des vers de huit syllabes) et avec des rimes.

Autre particularité, Le Roman de Renart a plusieurs auteurs: une
trentaine! L’un des premiers est connu: il s’appelle Pierre de
Saint-Cloud, surnommé Pierrot, et il commence, de 1170 à 1178, à
raconter les aventures d’un personnage appelé « Renart ». Il est le
premier à le faire par écrit, mais il n’a pas inventé ces aventures:
il reprend ce que d’autres racontaient avant lui. Après lui, au XIIIe
siècle, d’autres auteurs poursuivront ces récits. La plupart de ces
auteurs sont anonymes.

Enfin, chaque épisode du Roman de Renart forme une histoire
indépendante. L’unité est donnée par des personnages que l’on
rencontre sans cesse : Renart, le héros, Ysengrin, le loup qui est
l’oncle et l’adversaire du héros, Tiécelin, le corbeau, Chantecler, le
coq, Noble, le lion, Hermeline, la renarde...

Dans l’épisode que tu vas lire au cours de la première séance, Renart
cherche seul de la nourriture, après avoir volé une jeune oie à son
cousin, le loup Primaut. La faim est très présente dans le Roman de
Renart, comme dans la vie des hommes du Moyen Âge.

Avant de commencer, prends ton cahier. En haut d’une nouvelle page,
recopie en rouge le numéro et le titre de la séquence. Encadre-les.

Recopie ensuite en rouge le numéro et le titre de la
séance. Souligne-les. 

À présent, lis le texte reproduit ci-dessous. Pour t’aider, voici
quelques mots de vocabulaire que tu vas rencontrer :

- les « tanches » et les « harengs » : poissons.
- les « harangers » : poissonniers.
- un « écot » : ce que chacun paie pour un repas pris en commun.
- « aller à l’amble » : allure des quadrupèdes entre le pas et le trot

** Vengeance!

Renart et Primaut vivent de nombreuses aventures et mésaventures.
Dans celles qui précèdent, Primaut, le loup, accompagné de Renart, a
dérobé, dans une église, des vêtements qu’il a ensuite échangés contre
un oison bien gras; mais il a refusé de partager avec Renart.

L’aventure que vous allez lire s’intitule:

Comment Renart eut vengeance de Primaut, et comment il le fit battre
par les harengers.

Laissons là Primaut, pour revenir à Renart, qui cherche à se consoler
de la perte de l’oison, et se bat les flancs pour trouver autre chose
à se mettre sous la dent. Mais, quand après avoir assez couru, il vit
que le bois ne lui offrait pas grande chance de butin, il reprit le
sentier qui conduisait au chemin de la foire, et regagnant les abords
de la route, il résolut d’y attendre quelque aventure. Il n’était pas
au guet depuis longtemps, quand il entendit venir une lourde
charrette. C’était des marchands de poisson qui conduisaient à la
foire une provision de tanches et de harengs. Renart, loin de
s’effrayer de leur approche, se vautre dans la terre humide, s’étend
en travers du chemin, la queue raide, la pelisse toute blanchie de
fange. Il se place jambes en l’air, dents serrées, balèvres rentrées,
langue tirée et les yeux fermés. Les marchands en passant ne manquent
pas de l’apercevoir. « Oh ! regardez, » dit le premier, « par ma foi
c’est un goupil.  Belle occasion de payer avec sa peau l’écot de la
nuit!  Elle est vraiment belle, on en ferait une bonne garniture de
surcot; je ne la donnerais pas pour quatre livres. -- Mais, » dit un
autre, « elle les vaut, et mieux encore ; il ne faut que regarder la
gorge. Voyez comme elle est blanche ! Or, mettons-le dans la voiture,
et dès que nous serons arrivés, nous lui ôterons ce manteau qui doit
lui tenir trop chaud. »

Cela dit, on le lève, on le jette sur la charrette, on l’étend
au-dessus d’un grand panier, on le recouvre de la banne, puis on se
remet en route. Ce panier contenait pour le moins un millier de
harengs frais.  Renart, que les marchands ne surveillaient guère,
commence par en savourer une douzaine ; puis la faim cesse et la
satiété arrive.

C’est le moment de penser à s’échapper; et comme, tout en dévorant, il
n’oubliait pas la félonie de Primaut, il avise un expédient qui va lui
fournir un excellent moyen de vengeance. Il prend entre ses dents un
des plus beaux harengs, joint les pieds, fait un saut et le voilà sur
le pré. Mais avant de s’éloigner, il ne peut se tenir de gaber un peu
les marchands : « Bon voyage, les vilains ! je n’ai plus affaire de
vous et je vous engage à ne pas compter sur ma peau pour votre
écot. Vos harengs sont très bons; je n’en regrette pas le prix. À vous
le reste, sauf celui-ci que j’emporte pour la faim prochaine. Dieu
vous garde, les vilains! »

Cela dit, Renart joue des jambes, et les harengers de se regarder
confus et ébaubis. Ils le huent, ils le menacent; peines perdues, il
n’en presse pas d’un brin son allure. Il va le trot, le pas, l’amble;
à travers monts, bosquets, plaines et vallées, jusqu’à ce qu’il ait
enfin regagné l’endroit où il avait laissé Primaut.  

                                                     (à suivre...)

Le roman de Renart, © éditions Gallimard, coll. « Folio »

Notes :
1- oison : jeune oie
2- se battre les flancs : se donner du mal inutilement
3- pelisse : manteau garni de fourrure
4- balèvres : lèvres
5- surcot : vêtement de dessus porté au Moyen Âge
6- banne : toile, bâche
7- expédient : moyen provisoire de se sortir d’embarras
8- gaber : se moquer
9- ébaudi : stupéfait

** A: Le personnage de Renart

As-tu bien lu ? Pour vérifier ta lecture, réponds aux questions
suivantes, sur ton cahier, en rédigeant des phrases complètes.

1- a) Dans un dictionnaire, cherche l’étymologie du nom commun «renard».
   b) En t’aidant de ta précédente réponse, explique l’orthographe du
      nom « Renart ».

2- a) Par quel nom commun les marchands désignent-ils Renart dans le
      premier paragraphe?
   b) À ton avis, que veut dire ce mot ?
   c) Ce nom est-il encore utilisé aujourd’hui ?
   d) En t’aidant d’un dictionnaire, trouve un verbe utilisé aujourd’hui 
      et dont le radical est le nom commun que tu as relevé à la question 2a.

3- Renart agit-il comme un animal ou comme un être humain ? Justifie 
   ta réponse en donnant une ou plusieurs raisons à ton choix.

Compare tes réponses avec celles du corrigé. Lis maintenant le « Je
retiens » et mémorise-le.

je retiens

Le personnage de Renart

Le héros du Roman de Renart est un animal que l’on appelait un goupil,
en ancien français (la langue du Moyen Âge). Le Roman de Renart a
connu une telle célébrité que le nom propre « Renart » est devenu le
nom commun « renard », qui a remplacé le mot « goupil » du Moyen Âge.

Les autres personnages du Roman de Renart sont aussi des animaux
(loup, lion...) mais ils agissent comme des êtres humains. On dit
qu’ils sont personnifiés.

** B: La ruse de Renart

1- Relis les lignes 1 à 6.
   a) Résume en une ou deux phrases la situation initiale de ce récit.
   b) Relève les indications de lieu dans la situation initiale.
   c) Parmi les indications de lieu, retrouve en quel endroit Renart 
      choisit de s’arrêter et dis pourquoi.
2- Quelle ruse utilise Renart pour tromper les harengers (marchands de harengs)?
3- Sur quel vice (défaut) des marchands, Renart compte-t-il pour réussir?

Vérifie tes réponses dans le corrigé.

La séance est terminée. Si tu t’es déjà procuré le roman d’Odile
Weulersse intitulé Le Chevalier au bouclier vert, tu peux en commencer
la lecture.


* Séance 2

** Étudier les formes en -ant

Dans cette séance, tu vas travailler à nouveau sur le texte racontant
l’aventure de Renart et des harengers (le texte reproduit au début de
la séance 1). Tu travailleras sur une notion de grammaire : les formes
verbales qui se terminent par le suffixe –ant.

Avant de commencer, prends ton cahier. Écris en rouge le numéro et le
titre de la séance. Souligne-les.

** A: Repérer et identifier les formes verbales en -ant

Fais les exercices suivants sur ton cahier, en rédigeant des phrases complètes pour répondre.
Attention, certains exercices sont à faire directement sur le cours.
1-	 Relis la phrase suivante, extraite du texte 1 (lignes 3-6) puis fais les exercices demandés.
	
« Mais, quand après avoir assez couru, il vit que le bois ne lui offrait pas grande chance
de butin, il reprit le sentier qui conduisait au chemin de la foire, et regagnant les abords
de la grande route, il résolut d’y attendre quelque aventure. »
a)	 Dans cette phrase, souligne les verbes conjugués et encadre ceux qui ne sont pas
conjugués.
b)	Sur les trois verbes que tu as encadrés, deux sont à un mode impersonnel que tu
connais. Quel est ce mode ? Reporte-toi à la séance 5 de la séquence 6 si tu as besoin
d’aide.
c)	 Donne l’infinitif du verbe encadré qui se termine par –ant.
d)	Dans la phrase « Il regagna les abords de la grande route », quelle est la fonction
grammaticale du groupe nominal souligné ?
Compare tes réponses avec celles du corrigé. Lis ensuite le « Je retiens » suivant et mémorise-le
avant de poursuivre. Recopie-le dans ton cahier si cela t’aide à l’apprendre.
© Cned, Français 5e —
99
Séquence 9 — séance 2
j e retiens
Le participe
Le participe est un mode impersonnel dont le verbe se termine par –ant. Il est
invariable. On distingue deux formes du participe : le participe présent et le participe
passé.
LE PARTICIPE PRÉSENT LE PARTICIPE PASSÉ
rusant ayant rusé
jouant ayant joué
se moquant s’étant moqué
Comme le verbe conjugué, le participe peut avoir des compléments.
Ayant joué un mauvais tour aux marchands, Renart s’enfuit avec des anguilles.
		
		
		
COD 	
du verbe 	
« jouer »	
COS
du verbe
« jouer »
e)	 Réécris la phrase en remplaçant le groupe de l’infinitif « après avoir assez couru » par
le participe passé du verbe « courir ». Fais attention à ton orthographe lorsque tu
recopies l’ensemble de la phrase.
2-	 Réécris les phrases suivantes en remplaçant les éléments soulignés par un participe
présent.
EX : Les hommes se dépêchent et s’approchent de Renart.
Ë Se dépêchant, les hommes s’approchent de Renart.
-	 Ils le saisissent par les pieds, le lancent entre les paniers et se remettent en route.
-	 Sans perdre de temps, il s’allonge sur les paniers, en ouvre un avec les dents et tire à
lui plus de trente harengs.
-	 Renart, qui connaît tant de ruses, passe sa tête et son cou dans les colliers, puis les
installe sur son dos.
3-	 a)	 Dans le texte reproduit au début de la séance 1, souligne deux autres verbes se
terminant par le suffixe –ant.
b)	Quelle préposition précède ces deux verbes ?
c)	 Recopie ces deux verbes et la préposition sur ton cahier. Précise, à chaque fois, qui fait
l’action exprimée par le verbe.
d)	Dans les phrases où sont utilisées ces deux formes verbales en –ant, quelle est la
fonction grammaticale du groupe nominal ou du pronom désignant ceux qui font
l’action exprimée par le verbe en -ant ?
100
— © Cned, Français 5e
séance 2 —
Séquence 9
e)	 Quelle précision apportent ces deux formes verbales en –ant ? Choisis la bonne
réponse :
	 Elles précisent :
	 r quand les personnages font l’action
	 r pourquoi les personnages font l’action
		 r comment les personnages font l’action
		 r où les personnages font l’action
f)	 Quel est le sens du complément circonstanciel qui permet d’apporter cette précision ?
Vérifie tes réponses dans le corrigé puis lis et apprends le « Je retiens » qui suit.
j e retiens
Le gérondif
Le gérondif est semblable au participe présent mais il est précédé de la préposition
« en ». Il est invariable comme le participe. Il peut avoir des compléments du verbe.
Renart s’éloigne de la charrette en emportant des anguilles.
		
		
COD
du verbe « emporter »	
Le gérondif se rapporte toujours au sujet du verbe conjugué (« en emportant »
concerne le sujet « Renart »). Il est complément circonstanciel du verbe (« en
emportant » = complément circonstanciel de manière).
4-	 Réécris les phrases suivantes en remplaçant les éléments soulignés par un gérondif.
	
EX : Il les mange de bon appétit, sans avoir besoin de sel ou de sauge.
Ë	Il les mange de bon appétit en n’ayant besoin ni de sel ni de sauge.
-	 Des marchands revenaient des bords de la mer, ils rapportaient des grosses quantités
de harengs frais et de poissons.
-	 Alors qu’il s’éloignait des marchands, Renart imagina comment utiliser cette aventure
pour se venger de Primaut.
Tu as certainement trouvé les bonnes réponses ; regarde tout de même dans le corrigé.
5-	 Lis les deux phrases suivantes puis réponds aux questions sur ton cahier, en rédigeant tes
réponses.
-	 Les harangers s’énervent quand ils entendent le sermon provocant de Renart.
-	 Le sermon de Renart agace les harangers, provoquant leur colère.
a)	 Souligne, dans les deux phrases, les formes verbales en –ant.
b)	Dans quelle phrase pourrais-tu remplacer la forme verbale en –ant par l’adjectif
« moqueur / moqueuse » ?
c)	 Réécris ces deux phrases en remplaçant « le sermon » par « la morale ». Fais attention
aux accords.
© Cned, Français 5e —
101
Séquence 9 — séance 2
Tu as certainement trouvé les bonnes réponses ; regarde tout de même dans le corrigé. Lis
soigneusement le « Je retiens » suivant et mémorise-le avant de poursuivre. Recopie-le dans ton
cahier si cela t’aide à l’apprendre.
j e retiens
L’adjectif verbal
Le participe présent employé comme adjectif est appelé adjectif verbal. Il est variable :
il s’accorde comme un adjectif. Il a les mêmes fonctions que l’adjectif : épithète du
nom (ex : Les marchands méfiants poussent Renart du pied.) ou attribut du sujet (ex :
Les marchands sont méfiants.).
ATTENTION : il ne faut pas confondre l’adjectif verbal (qui a les fonctions d’adjectif)
et le participe présent (qui a le rôle de verbe). Parfois, l’adjectif verbal et le participe
présent se distinguent par l’orthographe.
EXEMPLES :
PARTICIPE PRÉSENT
ADJECTIF VERBAL
excellant
excellent
négligeant
négligent
précédant
précédent
différant
différent
fatiguant
fatigant
6-	 Dans le texte reproduit au début de la séance 1, retrouve un adjectif verbal et encadre-le.
Compare ta réponse avec celle du corrigé.
B
Utiliser les formes verbales en -ant
Pour conclure cette séance, tu vas faire un petit exercice d’écriture dans lequel tu utiliseras
les formes verbales en –ant. Voici le sujet :
Renart rejoint Primaut et lui explique comment il a dupé les harangers et mangé leurs
poissons. Primaut décide d’utiliser la même ruse que Renart.
En une dizaine de lignes, raconte l’aventure du loup en utilisant différentes formes verbales
en –ant.
Pour réussir cet exercice, tu dois :
-	 mettre en scène le loup et les harangers
-	 expliquer que Primaut utilise la même ruse que Renart
-	 raconter la réaction des harangers
-	 utiliser au moins un participe, un gérondif et un adjectif verbal
-	 vérifier ta conjugaison, tes accords et ton orthographe
102
— © Cned, Français 5e
séance 2 —
Séquence 9
Fais d’abord cet exercice au brouillon. Vérifie ensuite que tu as bien respecté les consignes en
complétant le tableau suivant.
Récapitulatif des consignes
Les consignes sont respectées
Fait
À faire
Tu as mis en scène le loup et les harangers.
Tu as respecté le sujet en expliquant la ruse de
Primaut et la réaction des harangers.
Tu as utilisé au moins un participe, un gérondif et un
adjectif verbal.
Tu as vérifié l’accord de chaque verbe avec son sujet.
Tu as vérifié les accords des noms, des déterminants,
des adjectifs.
Si toutes les consignes sont bien respectées, recopie ton texte sur ton cahier. Lis ensuite dans le
corrigé un exemple de ce qu’il était possible d’écrire.
Auto-évaluation du socle commun
Avant de refermer ton cours, reporte-toi à la fin de la séquence pour évaluer les items de la
compétence 1 du socle commun que tu as réussi à mobiliser dans cet exercice. Tu vas t’auto-évaluer
en observant ton récit.
Sois honnête dans ton auto-évaluation et ne t’inquiète pas si tu ne maîtrises pas encore certains
items. Tu pourras les acquérir au cours de cette année, voire lors de l’année de 4e.
Ton travail d’expression écrite te permet d’évaluer au moins huit items du socle commun :
-	 écrire lisiblement un texte
-	 respecter les consignes d’écriture
-	 rédiger un texte bref
-	 utiliser les principales règles orthographiques
-	 rechercher l’information utile, savoir l’analyser
-	 identifier, expliquer, rectifier une erreur
-	 savoir s’auto-évaluer
-	 s’appuyer sur des méthodes de travail (organiser son temps, planifier son travail, consulter
spontanément un dictionnaire, une encyclopédie).
Quand tu as rempli le tableau d’évaluation du socle commun, tu peux poursuivre ta lecture du
Chevalier au bouclier vert d’Odile Weulersse. Si tu ne t’es pas encore procuré le roman, ne
tarde pas à le faire. N’hésite pas à lire Le Chevalier au bouclier vert dès que tu en as envie.
Tu n’es pas obligé d’attendre qu’on te le suggère à la fin d’une séance.
© Cned, Français 5e —
103
Séquence 9 — séance 3
Séance 3
Étudier le comique de situation
Dans cette séance, tu vas découvrir un nouvel épisode du Roman de Renart racontant l’enfance
de Renart. Cela te permettra d’approfondir le comique de situation que nous avons déjà évoqué
lors des séquences 5 et 8 sur le théâtre.
Avant de commencer, prends ton cahier. Écris en rouge le numéro et le titre de la séance. Souligne-
les.
Lis le texte reproduit ci-dessous :
Le Roman de Renart, I © Folio junior, Gallimard
104
— © Cned, Français 5e

* séance 3 —
A
Séquence 9
Les personnages
Réponds à présent aux questions suivantes sur ton cahier en rédigeant des phrases complètes.
1-	 Quels sont les trois personnages mis en scène dans ce texte ?
2-	 Quelles sont les liens de parenté ou les liens conjugaux (= mari et femme) entre ces trois
personnages ?
B
La situation d’énonciation
Relis les lignes 1 à 3.
1-	 Qui prend la parole dans ces lignes ?
2-	 Quel pronom personnel désigne cette personne ?
3-	 À qui s’adresse-t-elle ?
4-	 Quel pronom personnel désigne cette personne ?
Compare tes réponses avec celles proposées dans le corrigé. Lis ensuite le « Je retiens » proposé ci-
dessous :
j e retiens
Une œuvre orale
Au Moyen Âge, la plupart des gens ne savaient ni lire ni écrire. Ils se réunissaient pour
écouter les conteurs. Les récits se transmettaient oralement. Le Roman de Renart est
marqué par son caractère oral.
C
L’organisation du récit
1-	 Dans le texte, où commence et où se termine le récit de l’aventure de Renart ? Réponds
en donnant les numéros des lignes.
2-	 a)	 Dans le récit de l’aventure de Renart, en dehors des dialogues, relève les quatre
connecteurs de temps importants qui introduisent les quatre périodes de cette
aventure. Donne les numéros des lignes qui délimitent chaque période :
1re partie
2e partie
3e partie
4e partie
Connecteurs de temps
.......................................
.......................................
.......................................
.......................................
Numéros des lignes
Ligne ...... à ligne ........
Ligne ...... à ligne ........
Ligne ...... à ligne ........
Ligne ...... à ligne ........
b)	Résume chacune de ces quatre parties en une phrase.
N’oublie pas de comparer tes réponses avec celles proposées dans le corrigé.
© Cned, Français 5e —
105
Séquence 9 — séance 3
D
La ruse de Renart
1-	 Qu’est-ce qui attire Renart chez Ysengrin ? Relève la phrase qui l’indique.
2-	 Que conseille Renart à Ysengrin ? D’après la suite de cette histoire, quelle idée a-t-il en
tête quand il lui donne ce conseil ?
3-	 a)	 À ton avis, que veut dire Renart lorsqu’il s’exclame : « Tel se plaint qui n’a pas le
moindre mal » (lignes 63-64) ?
b)	Connais-tu une expression qui a le même sens ?
c)	 Qu’est-ce que Renart fait semblant de croire ?
4-	 Selon toi, la fin est-elle triste ou comique ?
Vérifie tes réponses dans le corrigé. Lis et mémorise ensuite le « Je retiens » suivant :
j e retiens
Le comique de situation
Dans le comique de situation, c’est la situation dans laquelle se trouvent les
personnages qui fait rire parce qu’elle est ridicule, surprenante ou inattendue. Le
comique peut également naître d’un malentendu ou, comme dans l’épisode des
bacons, d’un renversement de situation, comme au théâtre.
E
Expression écrite
Pour conclure cette séance, tu vas rédiger un petit texte qui pourrait être la suite de celui que
tu viens d’étudier. Voici le sujet :
Pour se venger de Renart, Ysengrin le défie en duel. Raconte cette aventure dans un texte
d’une quinzaine de lignes organisé en deux paragraphes décrivant le combat puis la ruse
utilisée par Renart pour échapper à la mort.
Pour réussir cet exercice, tu dois :
-	 écrire un premier paragraphe racontant le combat qui se termine par la victoire
   d’Ysengrin
-	 écrire un deuxième paragraphe racontant la ruse utilisée par Renart pour échapper à la
       mort
-	 utiliser le comique de situation pour expliquer comment Renart échappe à la vengeance
    d’Ysengrin
-	 vérifier ta conjugaison, tes accords et ton orthographe
106
— © Cned, Français 5e
séance 3 —
Séquence 9
Réalise d’abord cet exercice au brouillon. Vérifie ensuite que tu as bien respecté les consignes en
complétant le tableau suivant.
Récapitulatif des consignes
Les consignes sont respectées
Fait
À faire
Ton texte, d’une quinzaine de lignes, comporte deux
paragraphes, qui commencent chacun par un alinéa.
Ton premier paragraphe raconte le combat entre
Ysengrin et Renart et se termine par la victoire
d’Ysengrin.
Ton deuxième paragraphe raconte la ruse utilisée par
Renart pour échapper à la mort.
Tu as utilisé le comique de situation pour expliquer
comment Renart échappe à la vengeance d’Ysengrin.
Tu as vérifié l’accord de chaque verbe avec son sujet.
Tu as vérifié les accords des noms, des déterminants,
des adjectifs.
Si toutes les consignes sont bien respectées, recopie ton texte sur ton cahier. Lis ensuite dans le
corrigé un exemple de ce qu’il était possible d’écrire.
Auto-évaluation du socle commun
Avant de refermer ton cours, reporte-toi à la fin de la séquence pour évaluer les items de la
compétence 1 du socle commun que tu as réussi à mobiliser dans cet exercice. Tu vas t’auto-évaluer
en observant ton récit.
Sois honnête dans ton auto-évaluation et ne t’inquiète pas si tu ne maîtrises pas encore certains
items. Tu pourras les acquérir au cours de l’année, voire lors de l’année de 4e.
Ton travail d’expression écrite te permet d’évaluer au moins huit items du socle commun :
-	 écrire lisiblement un texte
-	 respecter les consignes d’écriture
-	 rédiger un texte bref
-	 utiliser les principales règles orthographiques
-	 rechercher l’information utile, savoir l’analyser
-	 identifier, expliquer, rectifier une erreur
-	 savoir s’auto-évaluer
-	 s’appuyer sur des méthodes de travail (organiser son temps, planifier son travail, consulter
     spontanément un dictionnaire, une encyclopédie).
Quand tu as rempli le tableau d’évaluation du socle commun, nous t’invitons à poursuivre la lecture
du Chevalier au bouclier vert d’Odile Weulersse. N’oublie pas que tu dois lire ce roman avant
l’évaluation de la séquence 9 car tu auras un petit exercice à faire sur ce livre. De plus, pour t’aider
à préparer l’évaluation, la séance 8 sera consacrée au Chevalier au bouclier vert.
© Cned, Français 5e —
107
Séquence 9 — séance 4
Séance 4
Distinguer les homonymes
Dans cette séance, tu vas apprendre à te servir du sens des mots dans un texte pour mieux les
orthographier.
Avant de commencer, prends ton cahier. Ecris en rouge le numéro et le titre de la séance. Souligne-
les.
A
Les homonymes
Voici le résumé d’un épisode du Roman de Renart dans lequel le héros se trouve pris au piège.
Lis-le puis réponds aux questions sur ton cahier. N’oublie pas de rédiger tes réponses en faisant des
phrases complètes.
Après avoir mangé ses mets préférés, Renart sortit de la grange. Il avait très soif. Il alla au
puits et se pencha. Il vit son reflet dans l’eau et crut que c’était sa femme Hermeline qui était
encore en vie. Mais il était trop haut pour distinguer clairement l’image au fond du puits.
Il décida donc de descendre. Il attrapa le seau. D’un saut, il monta dans le récipient. Au
risque de se rompre le cou, il descendit dans le puits et, en deux coups, en atteignit le fond.
Il comprit alors son erreur : « Pauvre sot ! s’exclama-t-il. Ce n’était que ton reflet ! »
1-	 Dans le résumé, observe les mots en gras et regroupe ceux qui se prononcent de la même
façon mais qui s’écrivent différemment.
Tu as certainement trouvé les bonnes réponses. Regarde tout de même dans le corrigé. Lis et
mémorise ensuite le « Je retiens » suivant :
j e retiens
Les homonymes
On appelle homonymes des mots qui se prononcent de la même façon mais qui n’ont
pas le même sens.
On distingue deux sortes d’homonymes :
-	 Les homophones : des mots qui se prononcent de la même façon mais qui s’écrivent
différemment. Exemple : un sceau, un sot, un saut, un seau.
-	 Les homographes : des mots qui se prononcent et s’écrivent de la même façon mais qui
n’ont pas le même sens. Exemple : la ferme de l’agriculteur, une ferme poignée de main,
je ferme la porte.
108
— © Cned, Français 5e
séance 4 —
Séquence 9
2-	 Complète les phrases suivantes avec le mot qui convient au sens de chacune d’elles. Tu
peux t’aider d’un dictionnaire si besoin. Fais attention à ne pas commettre d’erreurs de
copie quand tu écris les phrases sur ton cahier.
	
Liste des homonymes à utiliser : saut, sceau, seau, sot.
a)	 La fermière portait dans chaque main un ...... rempli d’eau.
b)	Le président apposa son ..... sur le papier officiel.
c)	 Pour franchir la rivière, le chien fit un ..... fabuleux !
d)	Tu es ..... de te vexer pour une plaisanterie !
3-	 Complète les phrases suivantes avec le mot qui convient au sens de chacune d’elles. Tu
peux t’aider d’un dictionnaire si besoin. Fais attention à ne pas commettre d’erreurs de
copie quand tu écris les phrases sur ton cahier.
	
Liste des homonymes à utiliser : les, lait, laid.
a)	 Cette vache a ..... mamelles gonflées de .....
b)	Ce tableau a des couleurs très sombres ; je le trouve très .....
4-	 Complète les phrases suivantes avec le mot qui convient au sens de chacune d’elles. Tu
peux t’aider d’un dictionnaire si besoin. Fais attention à ne pas commettre d’erreurs de
copie quand tu écris les phrases sur ton cahier.
Liste des homonymes à utiliser : teins, teint, tint, thym.
a) Pour faire cette recette, il faut se procurer du ..... et du laurier.
b) Tu ..... ton pull en noir parce que la couleur rouge ne te plaît plus.
c) L’enfant avait le ..... mat et les yeux verts.
d) Le président ..... alors un discours à ses ministres.
Compare tes réponses à celles proposées dans le corrigé.
B
Les homophones grammaticaux
1-	 Entoure les homophones dans les phrases suivantes.
-	 Qui de Renart ou d’Ysengrin est tombé dans le puits où il avait vu son reflet ?
-	 Là, dans le puits, Renart a cru voir la renarde qu’il aimait mais il ne l’a pas trouvée.
-	 Sa femme n’était pas dans le puits. Ça a beaucoup déçu Renart.
-	 Quelle déception pour Renart ! Quel moment terrible ! Il aimait tant sa femme qu’en
voyant son reflet il a cru qu’elle était au fond du puits.
-	 C’est au fond du puits qu’il s’est rendu compte qu’il ne pouvait plus sortir. Alors il a tiré
de toutes ses forces sur la corde du seau.
Vérifie tes réponses dans le corrigé. Mémorise ensuite le « Je retiens » suivant. Recopie-le sur ton
cahier si cela t’aide à l’apprendre.
© Cned, Français 5e —
109
Séquence 9 — séance 4
j e retiens
Les homophones grammaticaux
Il faut bien distinguer les homophones grammaticaux. Voici les plus courants :
-	 Ou, conjonction de coordination (on peut la remplacer par « ou bien ») / où, adverbe de
lieu ou de temps (on peut le remplacer par « pendant lequel » ou « dans lequel »).
-	 La, article défini ou pronom personnel / là, adverbe de lieu (on peut le remplacer par
« là-bas ») / l’a ou l’as, qui est une contraction du pronom personnel et du verbe « avoir »
(on peut le remplacer par « l’avait » ou « l’avais »).
-	 Sa, déterminant possessif (on peut le remplacer par « ses ») / ça, pronom démonstratif.
(on peut le remplacer par « cela »).
-	 Quel(s), quelle(s), déterminant interrogatif ou exclamatif / qu’elle(s), contraction
de « que » qui est suivi du pronom personnel « elle(s) » (on peut le remplacer par
« qu’il(s) »).
-	 C’est, le présentatif (on peut le remplacer par « c’était ») / il s’est, pronom réfléchi
suivi de l’auxiliaire « être » (on peut le remplacer par « je me suis ») / sais, sait, le verbe
« savoir » (on peut le remplacer par « savais, savait ») / ses, déterminant possessif (on
peut le remplacer par « sa » ou « son ») / ces, déterminant démonstratif (on peut le
remplacer par « ce, cet ou cette »).
2-	 Quel, quelle, quels, quelles, qu’elle ou qu’elles ? À toi de faire le bon choix ! Fais
attention à ne pas commettre d’erreurs de copie quand tu écris les phrases sur ton cahier.
a)	 ..... drôle d’idée ! ..... fasse attention à elle !
b)	Je suis allé voir le film avec Tom Cruise : ..... acteur !
c)	 ..... sont ceux qui n’ont pas fait leur exercice ?
d)	Le tableau ..... ont choisi d’accrocher chez elles est de toute beauté.
e)	 J’ignore ..... conséquences cette information aura sur la consommation.
Reporte-toi au corrigé pour vérifier tes réponses.
C
Dictée à choix multiples
Réécris le texte suivant en choisissant la bonne orthographe pour les mots écrits entre
parenthèses.
Renart vient de voler à un écuyer les armes, le cheval et le faucon du chevalier qu’il servait. Il
croise alors son vieil ennemi, l’escargot Tardif.
Renart entre (dans / dent / d’en) le (boit / bois) (quand / qu’en) il (voix / voit / voie) arriver
le limaçon (là / l’a / la / l’as) lance au (poing / point), l’écu au bras, le heaume (lassé /
lacé). (Quand / Qu’en) il (voix / voit / voie) Renart, une grande joie saisit le (chœur / cœur)
de l’escargot. (Quel / Quelle / Quelles / Qu’elle) chance ! pense-t-il, il va pouvoir (se / ce /
ceux) venger de Renart qui lui a beaucoup (nuit / nui). (Sans / Cent / S’en) attendre, il
éperonne (son / sont) cheval et frappe Renart avec (sa / ça) lance. Renart perd l’équilibre et
tombe au sol. Aussitôt, il ramasse (ces / sait / sais / ses / s’est / c’est) armes et remonte en
(sel / selle). (Quelques / quelque / Quelle que) instants plus tard, il désarçonne (à / a) son
tour Tardif qui tombe sur le (do / dos). Il est (a / à) l’envers et ne (peut / peu / peux) (ce /
se / ceux) retourner. Alors Renart (ce / se / ceux) moque de lui (puis / puits) repart, laissant
Tardif (là / l’a / la / l’as) (où / ou) il est.
110
— © Cned, Français 5e
séance 4 —
Séquence 9
Quand tu auras fini cet exercice, compare ton texte avec celui écrit dans le corrigé.
Auto-évaluation du socle commun
Avant de refermer ton cours, reporte-toi à la fin de la séquence pour évaluer les items de la
compétence 1 du socle commun que tu as réussi à mobiliser dans cet exercice. Tu vas t’auto-évaluer
en observant ton récit.
Sois honnête dans ton auto-évaluation et ne t’inquiète pas si tu ne maîtrises pas encore certains
items. Tu pourras les acquérir au cours de l’année, voire lors de l’année de 4e.
Ton travail d’expression écrite te permet d’évaluer au moins six items du socle commun :
-	 écrire lisiblement un texte
-	 respecter les consignes d’écriture
-	 utiliser les principales règles orthographiques
-	 rechercher l’information utile, savoir l’analyser
-	 identifier, expliquer, rectifier une erreur
-	 savoir s’auto-évaluer
Quand tu as rempli le tableau d’évaluation du socle commun, tu peux reprendre la lecture du
Chevalier au bouclier vert d’Odile Weulersse. Tu dois avoir fini de lire ce roman avant la
séance 8.
© Cned, Français 5e —
111
Séquence 9 — séance 5
Séance 5
Étudier la satire
Dans cette séance, tu vas étudier un nouvel épisode du Roman de Renart. Ce sera pour toi
l’occasion d’étudier la satire.
Avant de commencer, prends ton cahier. Écris en rouge le numéro et le titre de la séance. Souligne-
les.
Lis le texte reproduit ci-dessous :
Texte reproduit dans Le Fil d’Ariane 5ème – Didier, Paris, 2010, p. 22 (ISBN : 978-2-278-06870-8)
Notes :
1-	une poule : coupée
2- escabeau : siège de bois
112
— © Cned, Français 5e
séance 5 —
A
Séquence 9
Les personnages
1-	 Voici les portraits de plusieurs animaux présents dans le texte.
a)	 Indique le nom de chaque personnage sous son portrait.
Réponds à présent aux questions suivantes sur ton cahier en rédigeant des phrases complètes quand
il ne s’agit ni de coloriage ni de repérage.
b)	Quels sont les autres animaux, présents à la cour, qui ne sont pas représentés dans la
galerie de portraits ?
2-	 a)	 Colorie en bleu le cadre des cinq animaux qui appartiennent à la même famille.
© Cned, Français 5e —
113
Séquence 9 — séance 5
b)	Dans le texte, souligne en bleu toutes les informations qui montrent que ces animaux
sont des volailles de basse-cour.
c)	 Pourquoi ces personnages viennent-ils à la cour du roi ?
3-	 a)	 Dans le premier paragraphe, souligne en rouge le passage expliquant les blessures
mortelles que Renart a infligées à l’une des poules.
b)	Comment s’appelle la victime de Renart ?
c)	 En t’aidant de ce que tu as souligné en rouge, explique le jeu de mots autour du nom
de la victime de Renart.
4-	 Explique à présent le jeu de mots autour du nom du coq.
5-	 a)	 Dans la galerie de portraits, dessine une couronne sur la tête de l’animal qui est le roi
de la cour.
b)	Dans le texte, surligne deux informations qui expliquent quel animal est le roi.
6-	 a)	 Que signifie « couard » ? Tu peux t’aider d’un dictionnaire pour répondre.
b)	Dans le texte, souligne en vert le passage qui justifie le nom du lièvre.
c)	 Quelle image des courtisans le personnage du lièvre donne-t-il ?
Vérifie tes réponses dans le corrigé puis lis et apprends le « Je retiens » qui suit.
j e retiens
La satire
Le Roman de Renart ne cherche pas seulement à faire rire. C’est aussi une critique de la
société qui dénonce l’inégalité et les défauts des puissants : la cruauté des seigneurs,
la lâcheté des courtisans, l’égoïsme des moines... C’est un texte satirique.
Une satire est un texte qui dénonce des comportements humains en les tournant en
ridicule.
Pour le faire sans risque, les auteurs du Roman de Renart mettent en scène, non des
humains, mais des animaux personnifiés.
B
Expression écrite
Pour conclure cette séance, tu vas rédiger un petit texte. Voici le sujet :
Rendu furieux par les méfaits de Renart, le roi Noble le convoque à la cour pour le faire
passer en jugement. Raconte le procès de Renart en une quinzaine de lignes et en deux
paragraphes.
Pour réussir cet exercice, tu dois :
-	 écrire un premier paragraphe racontant la confrontation de Renart et de ses
   accusateurs (Ysengrin, Primaut, les harangers, Chantecler, Pinte, Hersent)
-	 écrire un deuxième paragraphe expliquant la sentence du roi et la condamnation de
    Renart. Fais uniquement parler Noble
-	 vérifier ta conjugaison, tes accords et ton orthographe
114
— © Cned, Français 5e
séance 5 —
Séquence 9
Fais d’abord cet exercice au brouillon. Vérifie ensuite que tu as bien respecté les consignes en
complétant le tableau suivant.
Récapitulatif des consignes
Les consignes sont respectées
Fait
À faire
Ton texte, d’une quinzaine de lignes, comporte deux
paragraphes, qui commencent chacun par un alinéa.
Ton premier paragraphe raconte la confrontation de
Renart et de ses accusateurs.
Ton deuxième paragraphe explique la sentence du roi
et la condamnation de Renart.
Tu as vérifié l’accord de chaque verbe avec son sujet.
Tu as vérifié les accords des noms, des déterminants,
des adjectifs.
Si toutes les consignes sont bien respectées, recopie ton texte sur ton cahier. Lis ensuite dans le
corrigé un exemple de ce qu’il était possible d’écrire.
Auto-évaluation du socle commun
Avant de refermer ton cours, reporte-toi à la fin de la séquence pour évaluer les items de la
compétence 1 du socle commun que tu as réussi à mobiliser dans cet exercice. Tu vas t’auto-évaluer
en observant ton récit.
Sois honnête dans ton auto-évaluation et ne t’inquiète pas si tu ne maîtrises pas encore certains
items. Tu pourras les acquérir au cours de l’année voire lors de l’année de 4e.
Ton travail d’expression écrite te permet d’évaluer au moins huit items du socle commun :
-	 écrire lisiblement un texte
-	 respecter les consignes d’écriture
-	 rédiger un texte bref
-	 utiliser les principales règles orthographiques
-	 rechercher l’information utile, savoir l’analyser
-	 identifier, expliquer, rectifier une erreur
-	 savoir s’auto-évaluer
-	 s’appuyer sur des méthodes de travail (organiser son temps, planifier son travail, consulter
     spontanément un dictionnaire, une encyclopédie).
Pense à continuer la lecture du Chevalier au bouclier vert. N’oublie pas que cette lecture sera
évaluée dans le devoir de la séquence 9.
© Cned, Français 5e —
115
Séquence 9 — séance 6
Séance 6
Distinguer et utiliser les voix active et passive
Dans cette séance, tu vas apprendre à distinguer les voix active et passive qui servent à conjuguer les
verbes.
Avant de commencer, prends ton cahier. Écris en rouge le numéro et le titre de la séance. Souligne-
les.
A
Distinguer les voix des verbes
Tu peux effectuer cet exercice sur le cours.
1-	 Lis les deux phrases suivantes puis réponds aux questions.
-	 Renart trompe les autres animaux.
-	 Les autres animaux sont trompés par Renart.
a)	 Dans les deux phrases, encadre en rouge les verbes.
b)	Souligne en vert celui qui fait l’action exprimée par le verbe.
c)	 Souligne en noir celui qui subit l’action exprimée par le verbe.
d)	Pour chaque phrase, indique si le sujet du verbe est celui qui fait l’action ou celui qui
la subit.
e)	 Quelle est la fonction grammaticale du groupe nominal « les autres animaux » dans la
première phrase ?
Vérifie tes réponses dans le corrigé puis lis et apprends le « Je retiens » qui suit.
j e retiens
La voix active et la voix passive
On distingue les phrases à la voix active des phrases à la voix passive.
Dans les phrases à la voix active, le sujet du verbe est généralement celui qui fait
l’action exprimée par le verbe. Tous les verbes peuvent être à la voix active : les verbes
intransitifs (c’est-à-dire les verbes qui ne sont pas suivis par un COD ni par un COI -
Exemple : Pinte s’évanouit.), les verbes transitifs directs (c’est-à-dire les verbes qui sont
suivis d’un COD - Exemple : Renart tue Coupée.) et les verbes transitifs indirects (c’est-
à-dire les verbes qui sont suivis d’un COI - Exemple : Renart se moque d’Ysengrin.).
Dans les phrases à la voix passive, le sujet du verbe est généralement celui qui subit
l’action exprimée par le verbe.
2-	 a)	 Dans la deuxième phrase, avec quel auxiliaire est conjugué le verbe ?
b)	À quel temps et à quel mode est conjugué cet auxiliaire ?
116
— © Cned, Français 5e
séance 6 —
Séquence 9
Compare tes réponses avec celles du corrigé. Lis ensuite le « Je retiens » suivant et mémorise-le
avant de poursuivre. Recopie-le dans ton cahier si cela t’aide à l’apprendre.
j e retiens
La transformation à la voix passive
Seuls les verbes qui ont un COD à la voix active peuvent être conjugués à la voix
passive. La voix passive est formée de l’auxiliaire « être » qui est suivi du participe
passé du verbe. L’auxiliaire « être » indique le temps et le mode de la voix passive.
L’emploi de l’auxiliaire « être » entraîne l’accord du participe passé avec le sujet du
verbe.
Exemple : Les autres animaux sont trompés par Renart. (Dans l’exemple, l’auxiliaire
« être » est au présent de l’indicatif donc « sont trompés » est au présent de l’indicatif
de la voix active.)
Pour transformer une phrase à la voix passive, la phrase à la voix active subit trois
modifications :
-	 Le COD du verbe devient le sujet du verbe
-	 Le verbe est conjugué à la voix passive
-	 Le sujet devient un complément d’agent
3-	 Dans la deuxième phrase, quelle préposition introduit le nom « Renart » ?
Tu as certainement trouvé la bonne réponse ; regarde tout de même dans le corrigé. Lis
soigneusement le « Je retiens » suivant et mémorise-le avant de poursuivre.
j e retiens
Le complément d’agent
Le complément d’agent est celui qui agit. Le sujet de la voix active devient le
complément d’agent de la voix passive. Le complément d’agent est introduit par la
préposition « par » ou la préposition « de ». Le complément d’agent est facultatif. Il
n’est pas toujours exprimé. Cependant on peut toujours le formuler.
Ex : Ysengrin a été trompé.
Le complément d’agent n’est pas exprimé mais on peut dire : Ysengrin a été trompé
[par Renart].
4- a)	 Relis le texte que tu as étudié dans la séance 5 et relève, sur ton cahier, une
proposition à la voix passive.
b)	Souligne le sujet en vert et souligne le complément d’agent en noir.
c)	 Encadre en rouge le verbe. Indique ensuite le temps, le mode et la voix de ce verbe.
d)	Réécris cette proposition à la voix active.
Tu as certainement trouvé les bonnes réponses ; regarde tout de même dans le corrigé avant de
passer à la deuxième partie.
© Cned, Français 5e —
117
Séquence 9 — séance 6
B
Utiliser la voix passive
1-	 Transforme à la voix passive les phrases suivantes :
1– L’odeur des bacons attire Renart chez Ysengrin.
2– Hersent prépare un repas pour Renart.
3– Renart troue le toit d’Ysengrin.
4– Renart vole les bacons.
5– Les marchands transportent des anguilles.
6– Les marchands aperçoivent Renart sur la route.
7– Un marchand jette Renart dans la charrette.
8– Renart mange beaucoup de poissons.
2-	 a)	 Lis les phrases suivantes et indique, à chaque fois, à quels temps, mode et voix est
conjugué le verbe.
1– Coupée a été tuée par Renart.
2– Renart est accusé par Pinte.
3– Depuis longtemps, de nombreux crimes avaient été commis par Renart.
4– Le roi est agacé par ces multiples crimes.
5– Un procès sera tenu par le roi pour juger Renart.
6– Les victimes de Renart auront été vengées par la condamnation de leur agresseur.
b)	Réécris à la voix active les phrases que tu as étudiées dans le précédent exercice.
Compare tes réponses avec celles du corrigé. Tu peux ensuite poursuivre ta lecture du Chevalier
au bouclier vert d’Odile Weulersse.
Quand le temps et l’envie t’en prennent, saisis-toi de ton livre et glisse-toi dans son univers, sans
attendre d’y être invité(e).
118
— © Cned, Français 5e
séance 7 —
Séquence 9
Séance 7
Découvrir le personnage du Renard dans la littérature
Dans cette séance, tu vas travailler sur des textes de différents auteurs qui mettent tous en scène un
renard. Cela te permettra de définir les caractéristiques de ce personnage littéraire.
Avant de commencer, prends ton cahier. Écris en rouge le numéro et le titre de la séance. Souligne-
les.
À présent, lis les textes 1 et 2 ci-dessous puis réponds aux questions.
A
D’Esope au Roman de Renart
Réponds à présent aux questions suivantes sur ton cahier en rédigeant des phrases
complètes.
1- a) À quelle époque a été écrit chacun des textes 1 et 2 ?
b) En quelle langue a été écrit le texte d’Esope ?
2-	 Les deux animaux sont-ils désignés par des noms communs ou des noms propres dans
chacun des textes 1 et 2 ? Organise bien ta réponse.
3-	 a)	 Où est installé le corbeau (textes 1 et 2) ?
b)	Où est le renard (textes 1 et 2) ?
© Cned, Français 5e —
119
Séquence 9 — séance 7
4- a)	 Que possède le corbeau (textes 1 et 2) ?
b)	Quelle ruse utilise le renard pour se l’approprier (textes 1 et 2) ?
c)	 Le but du renard est-il le même dans les deux textes ? De quoi veut-il s’emparer ?
5-	 Sur quels défauts du corbeau, le renard compte-t-il pour réussir dans son entreprise ?
6- a)	 Que veut dire le renard au corbeau dans la dernière réplique du texte 1 ?
b)	« Avis aux sots » (texte 1) : à qui cet avertissement s’adresse-t-il ?
7- a)	 Imagine une morale pour le texte 1.
b)	Imagine une morale pour le texte 2.
Vérifie tes réponses dans le corrigé avant de passer à la deuxième partie.
B
Le renard dans les Fables de La Fontaine
1-	 Relis les textes 1 et 2. Quelle est la fable de La Fontaine qui raconte la même histoire ?
	
Tu la trouveras facilement dans un recueil de Fables si tu ne la connais pas.
Lis et mémorise à présent le « je retiens » suivant :
j e retiens
Le renard dans la littérature
De l’Antiquité à nos jours, de nombreux écrivains ont mis en scène le renard dans
leurs textes, comme par exemple Esope, Phèdre que tu as peut-être étudiés en 6e et La
Fontaine dans leurs Fables ou les conteurs médiévaux dans le Roman de Renart.
Le personnage de Renard est le symbole de la ruse et de l’intelligence.
2-	 Lis la fable « Le Corbeau et le Renard » qui est reproduite dans le corrigé. Apprends-la
par cœur.
	
Quand tu penses avoir bien mémorisé la fable, ferme le corrigé et vérifie que tu connais
bien la fable de La Fontaine en complétant le texte ci-dessous.
Le Corbeau et le Renard
Maître ................................, sur un arbre .................................,
Tenait en son bec un ................................................
Maître Renard, par .................................................................,
Lui tint à peu près ce ......................................... :
Hé ! Bonjour, Monsieur ......................................................
Que vous êtes ......................... ! Que vous me ...................................... !
Sans ..................................., si votre ......................................
Se rapporte à votre .................................................,
Vous êtes le ...........................................................................................
120
— © Cned, Français 5e
séance 7 —
Séquence 9
À ces ............................... le Corbeau ............................................................ ;
Et pour montrer sa .....................................................,
Il ouvre un large bec, ............................................................................
Le Renard s’en saisit, et dit : Mon bon Monsieur,
Apprenez que .........................................................................
Vit aux ............................................ de celui qui l’écoute :
Cette ............................................. vaut bien un fromage, sans doute.
Le Corbeau, ....................................... et ........................................,
.................................., mais un peu tard, ..........................................................
Compare ton texte avec la fable écrite dans le corrigé. Prends ensuite le temps d’évaluer les items
du socle commun que tu as mobilisés en faisant cet exercice.
Auto-évaluation du socle commun
Avant de refermer ton cours, reporte-toi à la fin de la séquence pour évaluer les items de la
compétence 1 du socle commun que tu as réussi à mobiliser dans cet exercice. Tu vas t’auto-évaluer
en observant ton récit.
Sois honnête dans ton auto-évaluation et ne t’inquiète pas si tu ne maîtrises pas encore certains
items. Tu pourras les acquérir au cours de l’année, voire lors de l’année de 4e.
Ton travail d’expression écrite te permet d’évaluer au moins sept items du socle commun :
-	 écrire lisiblement un texte
-	 respecter les consignes d’écriture
-	 utiliser les principales règles orthographiques
-	 rechercher l’information utile, savoir l’analyser
-	 identifier, expliquer, rectifier une erreur
-	 mémoriser des textes patrimoniaux
-	 savoir s’auto-évaluer
À présent que la séance est terminée, prends le temps de terminer, si tu ne l’as pas fait, ta lecture
du Chevalier au bouclier vert d’Odile Weulersse. Tu dois avoir fini le roman pour pouvoir faire
les exercices de la séance 8.
le coin des curieux
Si le cœur t’en dit, tu peux retrouver Renart sur le site de la BNf dans le dossier Bestiaire
médiéval à l’adresse suivante : http://classes.bnf.fr/renart/
Tu as la possibilité de feuilleter le manuscrit, d’admirer des enluminures, d’approfondir des
notions étudiées dans cette séquence, comme la satire, d’avoir accès à d’autres recueils de
Fables, d’effectuer des activités ludiques. Quel programme !
Bonne visite !
© Cned, Français 5e —
121
Séquence 9 — séance 8
Séance 8
Préparer l’évaluation de la lecture cursive
du Chevalier au bouclier vert d’Odile Weulersse
Dans cette séance, tu vas vérifier ta lecture du Chevalier au bouclier vert, le roman d’Odile
Weulersse que tu as lu pendant la séquence 9. Le but est de t’aider à préparer l’évaluation de la
lecture cursive qui aura lieu dans le devoir.
Essaie de faire les exercices en te servant uniquement de ta mémoire et de ce dont tu te souviens du
livre. Cependant, si tu n’arrives pas à répondre à quelques questions, tu as le droit de consulter le
roman.
A
	
122
Vérifier la lecture du roman
Vérifie ta lecture du roman en reliant chaque question posée dans la colonne A à sa
réponse proposée dans la colonne B.
— © Cned, Français 5e
séance 8 —
Colonne A
Quel exploit accomplit Thibault au
•
début du roman, sauvant ainsi 	
Eléonore ?	
Quelle est la récompense de Thibault
•
pour avoir sauvé Eléonore ? 	
Barnabé a prévenu Thibaut qu’Eléonore
était en danger. Que donne la jeune fille 	 •
à Barnabé pour le remercier ? 	
Quel est le nom de l’épée de Thibault ? 	 •
Pourquoi Thibault décide-t-il de devenir
un chevalier errant ? 	
Qui attaque le château du comte de
Blois ? Pourquoi ? 	
Thibault a été blessé par des mendiants
qui voulaient lui prendre son manteau.
Il est soigné par une femme qui a été 	
ensorcelée. De quel sort était-elle
victime ? 	
Séquence 9
Colonne B
Thibault ne veut pas devenir le vassal de
• Foulque et il veut acquérir du renom pour
être digne d’épouser Eléonore.
• Thibault lui dit qu’elle est belle alors qu’elle
ressemble à une vieille sorcière.
Foulque attaque le château du comte de
• Blois. Il veut forcer le comte à lui donner
Eléonore en mariage.
Thibault sauve le roi de six brigands qui
• voulaient l’enlever pendant sa promenade.
• • Thibault est adoubé.
• • L’épée s’appelle Santacrux.
•
Comment Thibault rompt-il le sort dont
•
Hadelize est victime ? 	
Gascelin accuse Thibault d’avoir tué son
père, le comte de Blois (La blessure faite
• par la flèche n’était pas grave. Thibault
aurait utilisé sa pierre magique pour
provoquer des blessures mortelles.)
Rosamonde a volé la pierre magique de
• Thibault et a touché le front d’Eléonore
avec.
Juste après que Raoul est nommé comte Thibault affronte deux bandits qui avaient
  de Blois, de quoi Gascelin accuse-t-il 	 • enlevé Eléonore et il la libère.
  • 
    Thibault ? 	 
Pourquoi Eléonore tombe-t-elle malade ? 	• •
•
Qui attaque et assiège la ville de Chartres ? 	
Comment Thibault et ses compagnons
sortent-ils de la ville de Chartres
•
lorsqu’elle est assiégée par Gascelin et
Flouque ? 	
Comment Thibault, qui a été accusé à
tort de trahison, regagne-t-il la confiance 	•
du roi ? 	
Qu’arrive-t-il à Rosamonde à la fin du
•
roman ? 	
Avec qui Barnabé part-il à la fin du
•
roman ? Pourquoi ? 	
Elle est brûlée sur le bûcher comme une
sorcière.
Barnabé part avec monsieur Guillaume qui
• est marchand car Barnabé veut devenir
marchand.
Elle lui donne une bague avec une
• émeraude.
Thibault et ses compagnons se déguisent
• en lépreux puis ils sont descendus avec des
cordes depuis les remparts de Chartres.
Foulque, Gascelin et Rosamonde assiègent
•
la ville de Chartres.
Hadelize, une jeune fée, a été transformée
• en sorcière vieille et hideuse.
Tu as certainement trouvé les bonnes réponses ; regarde tout de même dans le corrigé.
© Cned, Français 5e —
123
Séquence 9 — séance 8
B
Les personnages
1- Donne les noms des personnages suivants :
1) nom du héros
2) nom de la jeune fille qui est amoureuse du héros
3) nom de celui qui veut épouser de force l’amie du héros
4) nom de la méchante sœur de l’amie du héros
5) nom du frère aîné de l’amie du héros
6) nom du jeune frère de l’amie du héros
7) nom du jongleur du héros
8) nom de la magicienne qui aide le héros
9) nom de l’écuyer du héros
2- Reporte les noms que tu as trouvés dans le précédent exercice dans la grille suivante :
5
7
3
2
9
1
4
8
6
3-	 Dessine le portrait de Thibault. N’oublie pas de respecter les informations que te donne
le roman sur la couleur des cheveux de Thibault et sur celle de son bouclier.
Compare tes réponses et ton portrait avec ceux proposés dans le corrigé.
124
— © Cned, Français 5e
séance 9 —
Séquence 9
Séance 9
Je m’évalue
Comme à la fin de chaque séquence, tu vas faire un bilan de ce que tu as appris. Cela va te
permettre de faire le point sur ce que tu dois savoir et ce que tu dois être capable de faire pour le
devoir. Complète maintenant le tableau suivant. Bien sûr, si tu as oublié quelque chose ou si tu
n’es pas sûr de toi, tu peux utiliser ton cours. Lorsque tu auras fini, prends le corrigé et vérifie tes
réponses. Il est très important que ce tableau de synthèse ne comporte pas d’erreurs.
Je connais
-	 le Roman de Renart qui est un ensemble
de récits écrits par plusieurs auteurs
anonymes au XIIe siècle.
Je suis capable de
Ë	
Nommer quelques personnages du Roman
de Renart :
-	 La femme de Renart, ........................
Ë	 Je sais que ces récits mettent en scène des
........................, surtout le personnage de -	 L’oncle de Renart, le loup ........................
........................ qui est le symbole de la
-	 Le roi, le lion ........................
.........................
-	 Le coq, ........................
Ë	 Je sais que le héros du Roman de Renart
est à l’origine du nom commun « renard ».
Au Moyen Âge, cet animal était appelé un -	 Le courtisan, le lièvre ........................
.........................
-	 la définition de la satire :
	 ...............................................................
	 ...............................................................
	 ...............................................................
Ë	 Citer deux fabulistes qui ont mis en scène
un renard dans les fables satiriques :
-	 ........................, au VIe siècle avant J-C.
-	 ........................, au XVIIe siècle.
-	 la définition des homonymes :
	
	
	
Ë	 entourer les homophones qui conviennent
parmi les propositions faites dans le texte
...............................................................
ci-dessous :
............................................................... Renart (se / ce / ceux) lamente quand il
aperçoit une mésange perchée sur un chêne :
............................................................... l’arbre cachait un creux (ou / où) elle avait
installé (ces / s’est / c’est / ses / sait / sais)
œufs (a / à) l’abri :
-	 Bonjour, chère amie, descendez donc
m’embrasser.
-	 Il n’en (ai / es / est) pas question, Renart.
On ne peut être l’ami d’un brigand (deux /
de) votre espèce. Vous avez fait (tant /
temps) de mauvais (cou / cous / coups)
(a / à) (tant / temps) d’oiseaux qu’on
ne (ces / s’est / c’est / ses / sait / sais)
plus que penser. (Quel / Quelle / Qu’elle)
mauvais tour espérez-vous donc me jouer ?
© Cned, Français 5e —
125
Séquence 9 — séance 9
-	 le participe qui est un mode impersonnel
du verbe
Ë	 Je sais qu’on distingue deux formes
du participe : le ........................
(ex : s’évaluant) et le ........................
(ex : s’étant évalué).
Ë	 souligner en vert le participe présent,
de
en noir le participe passé, en rouge le
gérondif et d’encadrer en noir l’adjectif
verbal.
Avec l’arrivée de l’hiver, Renart et Ysengrin
trouvent difficilement à manger. Voulant
jouer un mauvais tour à son oncle, Renart lui
-	 Le gérondif, qui est aussi une forme
propose de pêcher ensemble dans l’étang. En
verbale en –ant.
arrivant devant le plan d’eau, les compères
Ë	 Je sais que le verbe au gérondif est précédé se montrent méfiants : l’eau est gelée et il est
dangereux de s’y aventurer. Renart se montre
de la préposition .........................
le plus entreprenant et marche sur la glace.
Ayant prouvé sa solidité, il invite son oncle à
-	 L’adjectif verbal qui est une forme en
le suivre...
–ant, qui s’accorde comme un adjectif
et qui peut avoir les mêmes fonctions :
........................et .........................
-	 la voix active et la voix passive
Ë	 Je sais que seuls les verbes transitifs
directs (c’est-à-dire les verbes suivis d’un
........................ à la voix active) peuvent
se mettre à la voix passive.
Ë	 Je sais que, quand je transforme une
phrase à la voix passive,
-	 le COD du verbe de la voix active devient
le ........................ de la voix passive
-	 le sujet du verbe de la voix active devient
........................ de la voix passive et
que ce complément est introduit par
les prépositions ........................ ou
........................
-	 le verbe de la voix passive est conjugué
avec l’auxiliaire ........................
126
— © Cned, Français 5e
Ë	 préciser le temps, le mode et la voix des
verbes dans les phrases suivantes :
-	 Les leçons seront révisées par les élèves
avant l’évaluation.
	 = .........................................................
	 ............................................................
-	 Les élèves ont étudié le Roman de Renart.
= ............................................................
-	 Les élèves apprennent les leçons.
= ............................................................
Ë	 Transformer à la voix passive les deux
dernières phrases :
-	 ...............................................................
	
...............................................................
séance 9 —
Séquence 9
Grille d’auto-évaluation du socle commun :
Tu dois remplir cette grille à la fin des séances 2, 3, 4, 5 et 7.
Quand tu estimes avoir maîtrisé un item, mets une croix en vert dans la case correspondante.
Si tu estimes que tu ne maîtrises pas encore un item (même si tu réussis ponctuellement
l’exercice), mets une croix en rouge dans la case correspondante.
Certains items sont évalués plusieurs fois dans la séquence. Il est possible que tu n’aies pas maîtrisé
un item dans une séance et qu’il le soit dans une autre séance. C’est normal. Cela te montre les
progrès que tu réalises.
Compétences du socle commun
Écrire lisiblement un texte
Copier un texte sans erreurs
Respecter les consignes d’écriture
Rédiger un texte bref
Utiliser les principales règles
orthographiques
Mémoriser des textes
patrimoniaux
Rechercher l’information utile,
savoir l’analyser
Identifier, expliquer, rectifier une
erreur
S’appuyer sur des méthodes de
travail (organiser son temps,
planifier son travail, consulter
spontanément un dictionnaire,
une encyclopédie)
Savoir s’auto-évaluer
Séance 2
Séance 3
Séance 4
Séance 5
Séance 7
© Cned, Français 5e —
127

