李宝树：法语动词的时、体与式，商务印书馆，2007
«Temps, aspect et mode du verbe français»

* 第一章

** p47 状态动词（avoir，être）使用简单过去时就能起到动作动词的作用

Une fois la lettre lue, la délibération de la famille fut courte.

Ce fut un coup terrible, il tomba par terre, et elle le laissa sangloter, assis contre le mur.

Il y eut un rire éclatant des écoliers qui décontenança le pauvre garçon, si bien qu'il ne savait s'il fallait garder sa casquette à la main, la laisser par terre ou la mettre sur sa tête.

Pour cette fois du moins, elle (la parole de ma mère) eut son effet et je m'atendris sur le sort de l'enfant maudit.

Ce remède eut un effet salutaire.

** p48 状态动词用在进行体会造成病句

- Il est en train d'avoir beaucoup d'argent.

- Elle est en train d'être heureuse.

- Cette fille est en train de ressembler à Marie.

- Ma valise est en train de contenir des vêtements de voyage.

- Ce travail est en train de me convenir.

- Pierre est en train d'aimer Marie.

- Elle est en train de haïr Robert.

- Il est en train de craindre la mort.

- Il est en train de croire à sa sincérité.

- Il est en train de savoir cette nouvelle.

- Elle est en train de me connaître.

** p48 有些状态动词(如aimer, croire等)如果用副词短语 à  nouveau, de plus en plus 或 de mieux en mieux 来修饰则可以用在进行体

Pierre aime vite (=tombe vite amoureux) et il est en train d'aimer à nouveau.

Robert croit aux soucoupes volantes et il est en train d'y croire de plus en plus.

Il est en train de lire.

Elle est en train de travailler.

Elle est en train de chanter.

Le boulanger est en train de faire le pain.

Il est en train de sortir.

** p50 状态动词一般不能和 venir de [+infinitif] (表示刚刚)连用

- Elle vient de chérir également tous ses enfants.

- Ma femme vient d'apprécier beaucoup le confort de notre apartement.

- Elle vient de jalouser Françoise.

- Il vient de respecter ses supérieurs.

- Il vient de s'appeler Pierre.

- Cette bouteille vient de contenir de l'eau.

Il vient d'être professeur.

Elle vient d'être malade.

Je viens de lui parler.

Il vient de pleuvoir.

Le train vient de partir.

Il vient de terminer son travail.

** p51 并列复合句中，如果第一句的谓语动词是状态动词（être, avoir, ressembler, aimer, adorer, préférer, haïr, jalouser, douter, craindre, respecter, connaïtre等）则第二句中不能用动词短语（faire de même, le faire aussi, en faire autant等）

- Pierre est riche et Robert fait de même. 应该是...est le même.

- Pierre avait faim et Robert le faisait aussi.

- Pierre ressemble beaucoup à son père et Robert en fait autant.

- Pierre aime Marie et Robert fait de même.

- Pierre hait l'hypocrisie et Robert fait de même.

- Pierre jalouse Michel et Robert le fait aussi.

- Pierre craint la mort et Robert le fait aussi.

- Pierre respecte ses parents et Robert en fait autant.

- Pierre connaît M. Durand et Robert fait de même.

Pierre chante et Robert fait de même.

Pierre lit le journal et Robert le fait aussi.

Pierre a acheté une voiture et Robert en a fait autant.

Pierre est parti en vacances et Robert l'a fait aussi.

** p52 状态动词（avoir faim, se trouver dans l'embarras, haïr, admirer, jalouser, craindre, adorer, aimer, préférer等）不能和完成体动词（forcer, contraindre  ou obliger qn à faire qch, inciter, pousser, encourager ou exhorter qn à faire qch, convaincre ou persuader qn de faire qch 等）连用

- Il force Pierre à avoir faim.

- Il contraint Pierre à haïr Robert.

- Il oblige Pierre à se trouver dans l'embarras.

- Il incite Marie à jalouser (à haïr) Charlotte.

- Il a poussé Pierre à craindre les chiens.

- Il encourage Pierre à adorer sa femme.

- Il exhorte Pierre à admirer le coucher du soleil derrière la montagne.

- Il a convaincu Marie d'aimer Pierre.

- Il a persuadé Pierre de préférer le café au thé.

L'agent de police a forcé ce cycliste à s'arrêter.

Pierre voulait rester, mais Robert l'a contraint à partir.

Ses parents l'ont obligé à vous écrire.

Ce premier succès l'incita à persévérer.

Le besoin d'argent l'a poussé à voler cette montre d'or.

Je l'ai encouragé à continuer ses études.

Nous l'avons exhorté à bien travailler.

Nous l'avons enfin convaincu d'abandonner son projet.

On l'a persuadé de prendre du repos pour ménager sa santé.

Je l'ai persuadé de venir.
** p54 状态动词不能和 délibérément, volontiers, intentionnellement, consciemment, expès, sciemment, volontairement, à dessein 等类似的副词或副词短语连用

- Il avait faim délibérément.

- Pierre aime Marie volontiers.

- Il adore volontiers le chocolat.

- Il est riche intentionnellement.

- Il ressemble à son frère consciemment.

- Elle hait Pierre exprès.

- Il craint sciemment les chiens.

- Elle respecte volontairement ses parents.

- Il s'appelle intentionnellement Pierre.

- Il connaît à dessein monsieur Dubois.

J'ai refusé délibérément sa proposition.

Il a délibérément choisi ce métier.

Il a délibérément abandonné ce travail.

Le coupable a agi de props délibéré (délibérément ou à dessein).

Je vous accompagnerai volontiers au cinéma.

Il m'a heurté intentionnellement.

Il a fait cela consciemment.

Je suis venu exprès pour parler de cette question.

Excusez-moi, je vous ai bousculé, mais je n'ai pas fait exprès.

Elle n'a pas commis cette faute volontairement (sciemment), mais par mégarde.

C'est à dessein que j'ai agi ainsi.

Il a dit cela exprès pour blesser son interlocuteur.

Ne me dites pas que c'était involontaire, vous l'avez fait exprès.

** p55 状态动词 等用来描写人或事物以及说明人或十五所处的状态时不能使用简单过去时

- Louis XIV eut un nez aquilin.

- Sa propriété consista en herbages, cultures et forêts.

- Son ouvrage philosophique consista en quatre volumes.

- Cette bouteille contint de l'essence.

- Cet autocar contint trente-cinq personnes.

- Cette fenêtre donna sur un jardin.

- Son bureau donna sur la mer.

Louis XIV avait (ou a) un nez aquilin (crochu ou busqué).

Sa propriété consistait (consiste) en herbages, cultures et forêts.

Son ouvrage philsophique consistait (consiste) en quatre volumes.

Cette bouteille contenait (contient) de l'essence.

Cet autocar contenait (contient) trente-cinq personnes.

Cette fenêtre donnait (donne) sur un jardin.

Son bureau donnait (donne) sur la mer.

** pp57-66 区别完成体和非完成体时要注意的几种情况

- Elle a trouvé sa clef pendant deux heures.

Elle a cherché sa clef pendant deux heures.

- Le chasseur a tué le lièvre pendant deux heures.

Le chasseur a poursuivi le lièvre pendant deux heures.

- Il est entré (ou sorti) pendant deux heures.

- Il a fermé (ou ouvert) la porte pendant deux heures.

- Elle a cassé le vase pendant trois heures.

- L'enfant est tombé pendant trois heures.

- Le ballon a crevé pendant deux heures.

- La bombe a explosé pendant trois heures.

Nous avons conru pendant deux heures.

Il a lu le journal pendant une heure.

Nous avons travaillé pendant quatre heures.

Ils ont dansé pendant trois heures.

Ils ont joué au tennis toute la matinée.

Il a toussé toute la nuit.

Le vent a soufflé toute la journée.

Pierre est sorti du labyrinthe en trois heures.

Les grenades (les bombes) ont éclaté pendant deux heures.

Pour creuser le tunner, on a posé des mines qui ont explosé pendant deux heures.

- Le chasseur continue à blesser le lièvre.

- Le chasseur commence à blesser le lièvre.

Le chasseur continue à poursuivre le lièvre.

Le chasseur commence à poursuivre le lièvre.

- Elle continue à ouvrir (ou fermer) la porte.

- Elle commence à ouvrir (ou fermer) la porte.

- Il continue à casser la bouteille.

- Il commence à casser la bouteille.

- Cet enfant continue à tomber.

- Cet enfant commence à tomber.

- Le ballon continue à crever.

- Le ballon commence à crever.

Il commence à lire le journal.

Il continue à lire le journal.

Elle commenc à chanter (ou danser).

Elle continue à chanter (ou danser).

Ils commencent à jouer au tennis.

Ils continuent à jouer au tennis.

Elle commence à travailler (écrire, parler).

Le vent commence à souffler.

Le vent continue à souffler.

- Ce stylo commence à tomber par terre.

- Ce livre continue à tomber par terre.

La pluie (la neige) commence à tomber.

La pluie (la neige) continue à tomber.

Il commence à faire son travail.

Il continue à faire son travail.

Elle commence à laver (ou faire) la vaisselle dans l'évier.

Elle continue à laver du linge.

Cette usine commence à produire (ou fabriquer) des appareils de télévision.

Cette usine continue à produire des machines à laver.

- Il commence à accomplir sa tâche.

- Il continue à accomplir sa tâche.

- Il commence à achever ce travail.

- Il continue à achever ce travail.

- Il commence à finir son devoir.

- Il continue à finir son devoir.

- Il commence à terminer sa lettre.

- Il continue à terminer sa lettre.

** pp67-83 体的转化

La réunion a duré pendant deux heures.

Le ministre des Affaires étrangères a parlé à la radio pendant une heure.

Il a travaillé pendant trois heures.

Pierre a dormi pendant quatre heures.

Il a plu toute la matinée.

Cet ouvrier a travaillé quatrante heures, cette semaine.

Il a beaucoup travaillé hier.

J'ai lu un roman policier pendant mon voyage.

Nous avons chanté pendant deux heures.

J'ai écrit toute la soirée.

Il a écrit trois lettres.

J'ai marché une heure ce matin.

Nous avons beaucoup marché hier.

Hier, je me suis baladé sur le boulevard Saint-Michel.

Cet aprés-midi, nous nous sommes promenés trois heures dans le parc de Versailles.

Elle avait travaillé pendant vingt ans dans cette usine.

Il aura lu le journal pendant une heure.

Pierre sortait souvent le soir.

Tous les matins Pierre se levait de bonne heure pandant son enfance.

La pluie tombait.

Toutes les nuits, elle venait au vieux cabaret...Elle entrait en coup de vent.

Une voiture a reneversé un enfant qui traversait la rue.

Pendant que je montais, Pierre descendait.

Le neige tombe à gros flocons.

Robert rentre (ou retourne) chez lui tous les jours pour déjeuner.

Quand il part en vacances, c'est moi que le remplace dans son travail.

Dans une discussion, il sort toujours du sujet (ou il sort toujours de la question).

Il se levait souvent très tard.

Ils sortaient souvent ensemble.

Il venait nous voir tous les jours.

Robert rentrait tous les soirs chez lui très fatigué de sa journée.

Cela me revient souvent à l'esprit.

Ce marchand élève sans cesse ses prix.

Il tombe souvent dans l'erreur.

Je fais (prends) de la gymnastique (de l'exercice) tous les matins pour ne pas grossir.

Je remonte ma montre tous les soirs avant de me coucher.

Nous allons au cinéma tous les dimanches.

Il retourne tous les ans dans son pays natal.

Elle répète sans cesse des paroles inutiles.

Elle répète toujours les même griefs.

Les feuilles jaunes tombaient.

Les idées m'arrivaient en foule.

De longs applaudissements partaient à l'adresse de l'orateur.

Les flammes montaient de l'immeuble en feu.

Les voyageurs descendent du train.

Les mots lui arrivent aisément.

- Ce élève commence à entrer dans la salle de classe.

Les élèves conmmencent à entrer dans la salle de classe.

- Il commence à descendre du train.

Quand le train s'arrête, les voyageurs commencent à descendre.

L'avion commence à descendre.

L'avion commence à monter.

La maison en construction commence à monter (la maison en construction gagne en hauteur).

- Le livre commence à tomber.

Les feuilles commencent à tomber.

- La bomber commence à exploser.

Les bombes commencent à exploser.

- Cet élève commence à sortir de l'école.

Les élèves commencent à sortir de l'école.

Les fleurs commencent à sortir.

Les blés commencent à sortir de terre.

- Il commence à partir.

Ils commencent à partir.

En mars, les bourgeons commencent à partir.

- L'invité commence à arriver.

Les invités commencent à arriver (des invités sont arrivés, tous les invités ne sont pas encore arrivés).

- L'enfant commence à naître.

Les herbes commencent à naître.

- Le ballon commence à éclater.

Les ballons commencent à éclater.

- La bulle de savon commence à crever.

Les bulles de savon commencent à crever.

Il (ou ils) commence (ou commencent) à faire ses (ou leurs) devoirs.

Elle (ou elles) commence (ou commencent) à laver la vaisselle.

Une épaisse fumée sortait de la cheminée.

Le pétrole jaillissait des puits de forage.

Un doux parfum sort de ces roses.

Une odeur de friture sortait de la cuisine.

Le sang lui sortait de la bouche.

Une pluie fine tombe.

La neige tombait.

Le brouillant tombe.

Une brume légère monte du fleuve.

La marée (la rivière) monte.

La marée descendait.

La pluie (la neige) commence à tomber.

La grêle commence à tomber.

La vent commence à tomber.

La mer est basse, mais elle commence à monter.

L'eau commence à descendre.

Le sang commence à sortir de sa bouche.

Une épaisse fumée commence à sortir de la cheminée.

Le pétrole commence à jaillir des puits de forage.

Une odeur de friture commence à sortir de la cuisine.

** p85 双体动词 porter/se porter

Il porte un manteau gris.

Il porte des lunettes de soleil.

Elle porte au doigt une bague garnie de diamants (une bague de fiançailles).

Elle porte le deuil de son père.

Il porte des favoris.

Le chameau porte deux bosses, le dromadaire une.

Il porte la tristesse peinte sur son visage.

Cette lettre porte la date du 10 septembre.

Ce monument porte une inscription en caractéres grecs.

La maman porte son bébé dans ses bras.

Il porte une valise (un bouquet de roses) à la main.

Il porte toujours son stylo dans sa poche.

Ces colonnes portent une galerie.

Ce vaisseau porte trois cents hommes d'équipage et des vivres pour six mois.

Cette riviére porte bateau.

Il porte toute la responsabilité de cette affaire.

Elle a cinquante ans mais ne porte pas cet âge.

Il porte quarante ans (= il paraît avoir quarante ans).

Il porte bien son vin.

Il m'a porté (= aporté) ce livre.

La camionnette a porté des légumes au marché.

Il a porté la paix et la prospérité dans ce pays.

Il a porté le trouble dans cette famille.

Sa négligence m'a porté un grand préjudice.

Il nous a porté assistance.

Cette affaire a porté atteinte à sa réputation.

Ce chagrin porta coup à sa santé.

Il s'est disputé avec son voisin et lui a porté des coups.

Cet échec le portera à plus de prudence.

Cette réponse porta sa colère à son paroxysme.

Maintenant le bleu se porte moins.

Cette année, les robes se portent plus longues.

Cela ne se porte plus.

Il se porte garant (ou caution) pour Pierre.

Comment vous portez-vous?

Je me porte à merveille.

Il se porte comme le Pont-Neuf, malgré son grand âge.

Elle se porte mal.

La foule se porte vers le stade.

Il se porte à la rencontre de son ami.

Ils se portent à la gare pour l'acueillir.

Le sang s'est porté à la tête.

Il s'est porté à la dernière extrémité contre Pierre.









** p91 双体动词 aller/se aller

Nous allons en voiture à Fontainebleau.

Il va à son travail (à son bureau).

Ces soldats vont à la guerre.

Nous allons à la pêche (à la chasse).

Quand y est-il allé?

Ils vont au théâtre (au cinéma).

Il est allé jusqu'au bout de cette rue.

Il va à la rencontre de son ami.

Je vais chez le coiffeur.

Ils vont aux urnes (aux voix).

L'autoroute va de Paris à Orléans.

Cette montagne va jusqu'aux nues.

Cette affaire est allée à l'échec.

Ses espoirs sont allé en fumée.

Elle est allée jusqu'à l'interrompre dans son exposé.

Ce cheval va au galop.

Il allait à grands pas.

Elle va à petits pas.

Vous allez comme le vent.

Cette voiture va vite.

Il va à pas de tortue.

L'ivrogne va en zigzaguant.

À cette heure-ci, on va plus vite en métro qu'en voiture.

J'irai par le train.

Tout va à merveille.

Ça va de mal en pis.

Les affaires vont bien.

Cette machine va (mache) bien.

Ma montre va mal.

Cette cravate va avec son complet.

Ça vous va bien.

Cette robe lui va bien.

Ces bottines ne me vont pas.

Ces deux couleurs vont bien ensemble.

Ça me va.

Est-ce que ça va?

Ça va comme ça.

Comment va votre père?

Je vais très bien.

Ce malade va de mieux en mieux (de mal en pis).

Les conditions d'existence (ou les conditions de vie) du peuple chinois vont en s'améliorant.

Le bruit va croissant.

Notre travail allait s'améliorant.

Je m'en vais (= je pars).

Je m'en vais au marché (à la pêche, à la chasse).

Je m'en suis allé dès que j'ai vu que je le gênais.

Il s'en est allé furieux.

Les taches d'encre (les taches d'huile) s'en sont allées avec ce détachant.

Tous ses projets s'en étaient allés en fumée.

Ce malade s'en va.

** p96 双体动词 avancer/s'avancer

Il avança la main vers une chaise.

Il avança le bras et saisit une lampe de poche.

Elle a avancé la table vers moi.

Il a avancé la tête hors de la voiture.

Nous avons bien avancé notre travail en peu de temps.

Le voyageur a avancé l'heure de son départ, parce qu'il était pressé.

Les chagrins ont avacé sa mort.

Elle fit une chute qui avança ses couches.

J'ai avancé ma montre de dix minutes.

Son employeur lui a avancé 3000 francs.

Je lui ai avancé (prêté) de l'argent.

Il a avancé une proposition raisonnable.

Notre travail avance très vite.

Ils avancent (s'avancent) rapidement dans la forêt.

Ne restez pas à cet endroit, avancez.

La nuit avance.

Il avance en âge.

Ma montre avance.

Il s'avança (ou avança) à toute vitesse vers moi.

Il s'est avancé vers la porte.

Je me suis avancé jusqu'à la sortie.

Notre voiture s'avança jusqu'à la gare.

Il s'avançait (ou avançait) lentment.

Notre voiture s'avance à toute vitesse sur une route large et bordée d'arbres.

La Chine s'avance à pas de géant.

Il s'avance vite dans ses études.

Le cygne s'avance sur l'eau.











** 98 Marcher

Il marche en avant.

Il marche en arrière (à reculons).

Il marche à grands pas.

Pierre marche vite tandis que Robert avance d'un pas lent.

Il marche sur la pointe des pieds.

Il marche à pas de loup.

Il marche pieds nus.

Ce vieillard marchait avec une canne.

Ils marchaient lentement dans la rue (sur le trottoir).

Les écoliers marchent en rang sur la route.

Ma voiture marche à 120 kilomètres à l'heure.

Le temps marche avec rapidité.

Cette horloge électrique marche bien.

Ce magasin marche très bien.

Comment ça marche aujourd'hui?

Ça marche comme sur des roulettes.

Ça marche mal.

Ses études marchent bien.

Sa convalescence marche bien.

Elle marche lentement vers moi.

Nous marchons vers la ville.

Les armées ennemies marchent sur cette ville.

Ces soldats marchent au combat.

Il marche hardiment à (ou vers) son but.

Cette affaire marche vers un dénouement heureux.

L'impérialisme marche vers la mort (à sa ruine).

Il a marché en quatre jours de Strasbourg à Paris.

** p101 se déplace

Ce vieillard rhumatisant se déplace diffcilement.

La tortue se déplace lentement.

Les  poissons se déplacent à l'aide des nageoires.

Il se déplace avec des béquilles.

Il ne se déplace guère qu'en voiture.

Cet enfant se déplace rapidement vers sa mère.

Ils se déplacent en voiture vers la ville.

** p102 conduire, se conduire

Il conduit très prudemment.

Elle conduit la voiture avec beaucoup de maîtrise.

Le berger conduit un troupeau de moutons.

Cet enfant conduit un aveugle dans la rue.

Ce guide-interprète conduit de nombreux touristes étrangers.

Il conduit un orchestre.

Ce directeur conduit bien son usine.

Il conduit bien sa famille.

Ils conduisent un complot.

C'est un corps qui conduit l'électricité (la chaleur).

Le cuivre conduit bien la chaleur.

La mère conduit sa fille chez le médecin.

Il conduit ses pas vers la sorties.

Il a conduit ses invités jusqu'à la porte.

Les agents ont conduit le criminel en prison.

Le général de division conduit ses soldats au combat (à l'assaut).

Ce chemin conduit au Palais d'Été.

Ses traces nous ont  conduits jusqu'au lieu où il s'était caché.

La vertu conduit au bonheur.

La paresse l'a conduit à la misère.

Cela l'a conduit au désespoir.

On récompense les élèves qui se conduisent bien.

Il s'est conduit vaillamment.

Il s'est conduit comme un malappris.

** p105 voler

Cet oiseau vole à tire-d'aile.

Quand les hirondelles volent à ras de terre, c'est souvent un signe d'orage.

L'avion volait très haut (à haute altitude) dans le ciel.

Cette nouvelle vole bientôt de bouche en bouche.

Ce cheval vole.

Les flocons de neige volent au vent (au gré du vent).

Le temps vole.

Cet avion a volé de Paris à Athènes.

Cet enfant vole vers son père.

Cette fille a volé dans les bras de sa mère.

Il a volé chez son ami annoncer une bonne nouvelle.

Il vola au secours de son ami.

Ton porte-monnaie, tu l'as perdu ou on te l'a volé.

Un pickpocket lui a volé son portefeuille.

Ce domestique a volé son maître.

Ce commerçant a volé ses clients.

Il a été volé cette nuit.

** p 107 mener

Le vieux général mène cette campagne.

Le président mène les débats.

Le fils du défunt menait le deuil.

Elle mène un aveugle par la main.

Sa femme le mène par le bout du nez (elle le mène à la baguette).

C'est une pauvre femme, son mari la mène comme il veut.

Ce patron menait durement ses ouvriers.

Il mène (conduit) un gros camion.

Il mène bien sa boutique.

Il mène bien sa barque.

Il mène rondement cette affaire.

Il mène de front (en même temps) deux activités.

On ne sait pas encore qui a tué, mais la police mène l'enquête.

Ces guérilleros (partisans, maquisards) mènent une lutte armée.

Ils mènent de front (simultanément) combat et production.

La marmaille menait grand tapage (grand bruit).

Il mène la grand vie (une vie simple, une vie tranquille, une vie sans souci, une vie heureuse, une vie errante).

Ses sœurs menaient une vie de patachon (une vie de bâton de chaise, une vie de débauche, une vie dévergondée), un amant aujourd'hui, un autre demain.

La maman mène (conduit ou amène) sa fille à l'école.

Je le mène en voiture à la gare.

Hier, j'ai mené mes enfants au musée d'histoire naturelle (à l'exosition industrielle, à l'exposition de photographie).

Le général de régiment mène ses troupes au feu (à la guerre, au combat, à l'assaut).

Il m'a mené chez lui.

On a mené le condamné au supplice (à l'échafaud).

Sa femme mène les vaches à l'abreuvoir.

Il a mené sa voiture au garage pour faire réviser les freins.

Nous mènerons jusqu'au bout la réforme économique.

Il a mené son travail à bonne fin (à bien).

Ce sentier mène au bord de l'eau.

Tous les chemins mènent à Rome.

Cette rue vous mène vers la place Tian-an-men.

L'ambition mène souvent à la ruine.

Ces dépenses mèneront cette entreprise au bord de la ruine.

Cet acte irréfléchi l'a mené en cour d'assises.

** p110 courir





* 第四章

La marmaille jouait dans le jardin public.

Son fils soufflait dans une paille et s'amusait à faire de grosses bulles de savon.

Sa fille s'asmusait à attraper des papillons dans le jardin.

Les chasseurs poursuivaient le cerf à cheval.

La cigale chantait au temps chaud.

Marie lisait avec intérêt un roman d'amour.

Des pigeons roucoulaient tout bas.

Des mouches bourdonnaient à mes oreilles.

Les applaudisements crépitaient.

Les projectiles pleuvaient.

Une bande d'enfants piaillaient dans la rue.

Les oiseaux s'egosillaient dans le bosquet.

Le singe sautait de branche en branche.

Un moineau sautillait sur le gazon.

Pierre allait à Paris.

Elle marchait de long en large dans sa chambre.

Il marchait le premier, ses camarades le suivaient.

Des promeneurs longeaient les allées du parc.

Il cheminait seul, d'un pas inégal et lent.

Un serpent rampait dans l'herbe.

Il nageait à contre-courant.

Les ennemis fuyaient en désordre avant même de se battre.

Les cheminées de l'usine de produits chimiques fumaient au-dessus de la ville.

Les vagues déferaient sur les rochers.

Les drapeaux multicolores flottaient au gré du vent.

Le sang coulait de la blessure.

Accoudé à sa fenêtre, il méditait.

La vieille dame restait derrière la vitre de sa chambre à observer les passants.

Je l'attendais à la gare.

Le blessé parlait à l'infirmière en attendant la visite du docteur.

Les félicitations arrivaient de toutes parts.

Jadis, les châteaux de la Loire étaient habités par les rois de France.

Autrefois, ici, il y avait des jardins, maintenant il y a un grand immeuble.

Autrefois, j'étais un sportif éprouvé, mais maintenant je dois me contenter de regarder les autres.

Autrefois, le commerce entre l'Europe et l'Orient se faisait par caravanes.

Les gens d'autrefois connaissaient un rythme de vie beaucoup moins rapide que le nôtre.

Avant, il fallait plusieurs jours pour aller de Paris à new York, maintenant, il suffit de quelques heures.

Avant je l'aimais bien, mais maintenant je ne l'aime plus du tout.

Que faisait-il avant?

Son père faisait du commerce avant.

Avant l'Occupation, monsieur Dubois était directeur d'une entreprise de transport.

Il y avait une fois une princesse nommée Blanche-Neige.

Il était une fois un roi et une reine.

En 1985, il était à Marseille.

Hier, il neigeait.

Ce matin, une bruine légère tombait sur la ville.

Dès le lendemain du tremblement de terre, les dons affluaient de toutes les régions au profit des sinistrés.

Marie avait les cheveux blonds.

Ses longs cheveux flottaient sur ses épaules.

Sa forte moustache blonde, très cosmétiquée, sa face large et pâle qui donnaient l'air d'un mousquetaire malade.

Elle avait les yeux rouges, les joues un peu enflées, l'air fatigué.

Ses yeux brillaient d'un vif éclat.

Sa joie se lisait sure on visage.

Elle portait la tristesse sur son visage.

Un sourire flottait sur ses lèvres.

Elle avait l'air séreuix (ou séreuse).

Il avait l'air tout pensif.

Il portait un pantalon gris et un veston bleu.

Monsieur Guillaume portait de larges culottes de velours noir. Son habit à pans carrés enveloppait son corps, légèrement voûté, d'un drap verdâtre.

C'était un homme de trente ans environ, fort beau, avec toute l'apparence d'un gentilhomme.

À minuit, le clair de lune était magnifique.

Il faisait un froid de canard.

Le lac brillait sous le soleil.

Quelques nuages erraient dans le ciel.

Une pluie fine continuait.

Une brume épaisse rampait dans la vallée.

Les flocons de neige tourbillonnaient.

Ses pensées tourbillonnaient.

Une nuée d'oiseaux tourbillonnaient (tournoyaient) dans l'air.

La barque dansait sur les vagues.

Les flammes dansaient dans la cheminée.

Notre vaisseau fendait les flots.

Un parfum léger flottait dans la pièce.

Le soleil de mai versait sa claire lumière sur les pommiers épanouis, ronds comme d'immenses bouquets blancs, roses et parfumés, et qui mettaient sur la cour entière un toit de fleurs. Ils semaient sans cesse autour d'eux une neige de pétales menus, qui voltigeaient et tournoyaient en tombant dans l'herbe haute, où les pissenlits brillaient comme des flammes, où les coquelicots semblaient des gottes de sang.

Les feuilles arrachées, jaunes déjà, s'envolaient comme des oiseaux, tourbillonnaient, tombaient puis couraient tout le long de l'allée, ainsi que des bêtes rapides.

À Virelogne, j'aimais toute la campagne, semée de petits bois et traversée par des ruisseaux qui couraient dans le sol comme des veines, portant le sang à la terre. On pêchait là-dedans des écrevisses, des truites et des anguilles! Bonheur divin! On pouvait se baigner par places, et on trouvait souvent des bécassines dans les hautes herbes qui poussaient sur les bords de ces minces cours d'eau.

Paris était bloqué, affamé et râlant. Les moineaux se faisaient rares sur les toits, et les égouts se dépeuplaient. On mangeait n'importe quoi.

Ce qui la martyrisait surtout, c'était un besoin fou de l'embrasser, de l'étreindre en ses bras, de sentir contre sa chair la chaleur de son petit corps. Elle ne dormait plus la nuit; elle y pensait tout le jour; et, le soir son travail fini, elle s'asseyait devant le feu, qu'elle regardait fixement comme les gens qui pensent au loin.

Avant la libération, son père était mineur. Il traînait (menait) une vie misérable.

Il y avait cinq clients dans la salle d'attente du dentiste.

J'étais gêné, mal à l'aise, je ne savais pas quoi dire.

Elle avait honte, elle ne savait plus où se mettre.

La discussion me mettaiot mal à l'aise, j'avais envie de partir.

Catherine jouait du piano: elle portait une longue robe de velours noir qui cachait le tabouret. Elle avait sur sa tête une couronne de fleurs blanches. Des milliers de notes dorées sortaient du piano comme une fumée (un essaim) d'abeilles. De temps à autre, elle tourait son visage vers moi et me souriait tendrement.

Le colonel était confortablement étendu sur le sofar; sa fille chantait devant un piano délabré. Orso tournait les feuilles de son cahier de musique.

Les uns tiraient au bout d'une corde une vache, un veau. Et leurs femmes, derrière l'animal, lui fouettaient les reins d'une branche encore garnie de feuilles, pour hâter sa marche. Elles portaient au bras de larges paniers d'où sortaient des têtes de poulets par-ci, des têtes de canards par-là. Et elles marchaient d'un pas plus court et plus vif que leurs hommes, la taille sèche, droite et drapée dans un petit châle étriqué, épinglé sur leur poitrine plate, la te enveloppée d'un linge blanc collé sur les cheveux et surmontée d'un bonnet.








