high-level steps:

- usb iso install
- apt-get update/upgrade
- omv-extras install
- gparted iso
- ghost
- zfs
- kvm
- ghost
- X & miscs
- zpool create





basics: dpkg/apt/apt-cache/apt-file/aptitue

- update apt db: apt-get update
- upgrade: apt-get upgrade
- distro upgrade: apt-get dist-upgrade

- list all pkgs: dpkg -l apt
- list pkg files: dpkg -L apt
- search pkg by keyword: apt-cache search linux-sources-`uname -r`
- check pkg deps: apt-cache depends debian-zfs
- check pkg rdeps: apt-cache rdepends debian-zfs
- show pkg info: apt-cache show debian-zfs
- find file belongs to which pkg: apt-file search `which apt-cache` 
- aptitude/synaptic




omv-extras: http://omv-extras.org/simple/index.php?id=how-to-install-omv-extras-plugin
- wget http://omv-extras.org/debian/pool/main/o/openmediavault-omvextrasorg/openmediavault-omvextrasorg_0.5.39_all.deb
- dpkg -i openmediavault-omvextrasorg_0.5.39_all.deb
- apt-get update




omv plugins: http://songming.me/openmediavault-plexmediaserver-setup.html
uuid: https://wiki.debian.org/Part-UUID





* First install via USB ISO

** (Optional) Disable serial port to boot: http://www.overclock.net/t/1423729/cant-get-openmediavault-debian-installer-to-boot
** Do a default/normal install and reboot
** Log into the webui by "admin/openmediavault" for the 1st time, to change passwd, adduser, config ip@ and enable ssh from within webui:
  - change passwd for web "admin": system->general settings->web administrator passwd
  - config ip@: system->network
  - add user: access right mgmt->users
  - enable sshd: services->ssh
** Login via ssh to check the initial status



* Upgrade to backports kernel
     - /etc/apt/sources.list: http://forums.openmediavault.org/viewtopic.php?f=14&t=578
      . add: deb http://backports.debian.org/debian-backports squeeze-backports main non-free
      . update db: apt-get update
      . check kernel version: apt-cache search linux-image-3
      . install new kernel: apt-get -t squeeze-backports install linux-image-3.2.0-0.bpo.4-amd64 firmware-linux-free firmware-linux-nonfree

** Install omv-extras-plugin via ssh: http://omv-extras.org/simple/index.php?id=how-to-install-omv-extras-plugin
$ wget http://omv-extras.org/debian/pool/main/o/openmediavault-omvextrasorg/openmediavault-omvextrasorg_0.5.39_all.deb
sudo dpkg -i open...
sudo apt-get update




* Install ZFS: http://zfsonlinux.org/debian.html
http://bernaerts.dyndns.org/linux/75-debian/279-debian-wheezy-zfs-raidz-pool
[code]
[b]root@ovm32:~# wget http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_2%7Ewheezy_all.deb[/b]
--2014-03-30 21:18:15--  http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_2%7Ewheezy_all.deb
正在解析主机 archive.zfsonlinux.org... 205.251.242.180
正在连接 archive.zfsonlinux.org|205.251.242.180|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：50552 (49K) [application/x-debian-package]
正在保存至: “zfsonlinux_2~wheezy_all.deb”

100%[============================================================================================>] 50,552      38.2K/s 花时 1.3s    

2014-03-30 21:18:20 (38.2 KB/s) - 已保存 “zfsonlinux_2~wheezy_all.deb” [50552/50552])

[b]root@ovm32:~# dpkg -i zfsonlinux_2~wheezy_all.deb [/b]
选中了曾被取消选择的软件包 zfsonlinux。
(正在读取数据库 ... 系统当前共安装有 57384 个文件和目录。)
正在解压缩 zfsonlinux (从 zfsonlinux_2~wheezy_all.deb) ...
正在设置 zfsonlinux (2~wheezy) ...
[b]root@ovm32:~# apt-get update[/b]
...
root@ovm32:~# apt-get install debian-zfs
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
将会安装下列额外的软件包：
  cpp dkms gcc libnvpair1 libuutil1 libzfs1 libzpool1 lsb-release make patch python python-minimal python-support python2.6
  python2.6-minimal spl spl-dkms zfs-dkms zfsutils
建议安装的软件包：
  cpp-doc zfs-auto-snapshot gcc-multilib manpages-dev autoconf automake1.9 libtool flex bison gdb gcc-doc lsb make-doc ed
  diffutils-doc python-doc python-tk python-profiler python2.6-doc python2.6-profiler binfmt-support zfs-initramfs
推荐安装的软件包：
  build-essential fakeroot libc6-dev libc-dev
下列【新】软件包将被安装：
  cpp debian-zfs dkms gcc libnvpair1 libuutil1 libzfs1 libzpool1 lsb-release make patch python python-minimal python-support
  python2.6 python2.6-minimal spl spl-dkms zfs-dkms zfsutils
升级了 0 个软件包，新安装了 20 个软件包，要卸载 0 个软件包，有 38 个软件包未被升级。
需要下载 7,786 kB 的软件包。
解压缩后会消耗掉 30.4 MB 的额外空间。
您希望继续执行吗？[Y/n]
获取：1 http://mirrors.163.com/debian/ squeeze/main cpp i386 4:4.4.5-1 [14.9 kB]
获取：2 http://mirrors.163.com/debian/ squeeze/main gcc i386 4:4.4.5-1 [4,974 B] 
获取：3 http://mirrors.163.com/debian/ squeeze/main make i386 3.81-8 [392 kB]    
获取：4 http://mirrors.163.com/debian/ squeeze/main patch i386 2.6-2 [122 kB]    
获取：5 http://mirrors.163.com/debian/ squeeze/main python2.6-minimal i386 2.6.6-8+b1 [1,423 kB]
获取：6 http://mirrors.163.com/debian/ squeeze/main python2.6 i386 2.6.6-8+b1 [2,388 kB]
获取：7 http://archive.zfsonlinux.org/debian/ wheezy/main dkms all 2.2.0.3-1.2+zfs6 [78.8 kB]
获取：8 http://mirrors.163.com/debian/ squeeze/main python-minimal all 2.6.6-3+squeeze7 [33.8 kB]
获取：9 http://mirrors.163.com/debian/ squeeze/main python all 2.6.6-3+squeeze7 [169 kB]
获取：10 http://mirrors.163.com/debian/ squeeze/main python-support all 1.0.10 [33.0 kB]
获取：11 http://mirrors.163.com/debian/ squeeze/main lsb-release all 3.2-23.2squeeze1 [21.5 kB]
获取：12 http://archive.zfsonlinux.org/debian/ wheezy/main spl-dkms all 0.6.2-3~wheezy [552 kB]
获取：13 http://archive.zfsonlinux.org/debian/ wheezy/main zfs-dkms all 0.6.2-4~wheezy [1,418 kB]                                    
获取：14 http://archive.zfsonlinux.org/debian/ wheezy/main spl i386 0.6.2-3~wheezy [15.0 kB]                                         
获取：15 http://archive.zfsonlinux.org/debian/ wheezy/main libuutil1 i386 0.6.2-4~wheezy [53.6 kB]                                   
获取：16 http://archive.zfsonlinux.org/debian/ wheezy/main libnvpair1 i386 0.6.2-4~wheezy [49.7 kB]                                  
获取：17 http://archive.zfsonlinux.org/debian/ wheezy/main libzpool1 i386 0.6.2-4~wheezy [506 kB]                                    
获取：18 http://archive.zfsonlinux.org/debian/ wheezy/main libzfs1 i386 0.6.2-4~wheezy [155 kB]                                      
获取：19 http://archive.zfsonlinux.org/debian/ wheezy/main zfsutils i386 0.6.2-4~wheezy [349 kB]                                     
获取：20 http://archive.zfsonlinux.org/debian/ wheezy/main debian-zfs i386 7~wheezy [7,054 B]                                        
下载 7,786 kB，耗时 2分 10秒 (59.6 kB/s)                                                                                             
正在预设定软件包 ...
选中了曾被取消选择的软件包 cpp。
(正在读取数据库 ... 系统当前共安装有 57390 个文件和目录。)
正在解压缩 cpp (从 .../cpp_4%3a4.4.5-1_i386.deb) ...
选中了曾被取消选择的软件包 gcc。
正在解压缩 gcc (从 .../gcc_4%3a4.4.5-1_i386.deb) ...
...
[/code]

* KVM

     - kvm: https://wiki.debian.org/KVM
      . apt-get install qemu-kvm libvirt-bin: after that, verify:
            bruin@omv:/$ lsmod|grep kvm
            kvm_intel             120947  0 
            kvm                   292670  1 kvm_intel
            bruin@omv:/$ ls /dev/kvm
            /dev/kvm
            bruin@omv:/$ 
       . add user into libvirt group:
            bruin@omv:/$ sudo adduser bruin libvirt
            Adding user `bruin' to group `libvirt' ...
            Adding user bruin to group libvirt
            Done.
            bruin@omv:/$ 
       . setup bridge networking: already installed.
            bruin@omv:/$ dpkg --list|grep bridge-utils
            ii  bridge-utils                        1.4-5                        Utilities for configuring the Linux Ethernet bridge
            bruin@omv:/$ 
       . change /etc/network/interfaces:

* X

      . apt-get install xorg gnome gdm
      . /etc/inittab: change run level from 2 to 5
      . reboot and login

* locale/fonts
- dpkg-reconfigure locales
- apt-get install xfonts-wqy

* Misc pkgs:

vim less htop manpages man-db apt-file util-linux aptitude synaptic gparted



* gparted:
  apt-get install gparted: for review the partitions, not able to make changes online.
  gparted-live-0.16.2-11-i686-pae.iso
  apt-file search blkid
bruin@omv:~$ /sbin/blkid
/dev/sda1: LABEL="root" UUID="5cac462c-6692-45bf-9de2-3f7e425104a4" TYPE="ext4" 
/dev/sda3: LABEL="backup" UUID="81a55061-e905-4fd5-9076-f13488cafd47" TYPE="ext4" 
/dev/sda4: LABEL="tank" UUID="8b5026ab-5a79-40e2-b328-58cee27187f8" TYPE="ext2" 
/dev/sda5: LABEL="swap" UUID="a76cea18-fb07-4f68-b36e-4f5ba78aa7f9" TYPE="swap" 
bruin@omv:~$ df -mh
Filesystem            Size  Used Avail Use% Mounted on
/dev/sda1              49G  3.1G   43G   7% /
tmpfs                 3.9G     0  3.9G   0% /lib/init/rw
udev                   10M  208K  9.8M   3% /dev
tmpfs                 3.9G     0  3.9G   0% /dev/shm
tmpfs                 3.9G  8.0K  3.9G   1% /tmp
bruin@omv:~$ cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc            /proc           proc    defaults        0       0
# / was on /dev/sda1 during installation
UUID=5cac462c-6692-45bf-9de2-3f7e425104a4 /               ext4    errors=remount-ro 0       1
# swap was on /dev/sda5 during installation
UUID=a76cea18-fb07-4f68-b36e-4f5ba78aa7f9 none            swap    sw              0       0
/dev/sdb1       /media/usb0     auto    rw,user,noauto  0       0
tmpfs           /tmp            tmpfs   defaults        0       0
bruin@omv:~$ 
bruin@omv:~$ sudo fdisk -l

Disk /dev/sda: 320.1 GB, 320072933376 bytes
255 heads, 63 sectors/track, 38913 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000c72ad

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *           1        6374    51198131   83  Linux
/dev/sda2           37335       38914    12683265    5  Extended
/dev/sda3            6375       36970   245762370   83  Linux
/dev/sda4           36971       37335     2924544   83  Linux
/dev/sda5           37335       38914    12683264   82  Linux swap / Solaris

Partition table entries are not in disk order
bruin@omv:~$ 


